/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AccessRequest {
  'status' : AccessStatus,
  'requester' : UserId,
  'momentId' : MomentId,
  'requestedAt' : Timestamp,
  'resolvedAt' : [] | [Timestamp],
}
export type AccessStatus = { 'revoked' : null } |
  { 'pending' : null } |
  { 'denied' : null } |
  { 'approved' : null };
export interface ActivityEvent {
  'id' : bigint,
  'kind' : ActivityKind,
  'createdAt' : Timestamp,
  'momentId' : [] | [MomentId],
  'actorId' : UserId,
  'targetUserId' : [] | [UserId],
}
export type ActivityKind = { 'rsvpdToMoment' : null } |
  { 'createdMoment' : null } |
  { 'followedUser' : null };
export interface AddCommentInput {
  'text' : string,
  'parentId' : [] | [CommentId],
  'mediaId' : MediaId,
}
export interface AgendaItem {
  'id' : bigint,
  'title' : string,
  'time' : string,
  'description' : [] | [string],
}
export interface Announcement {
  'id' : bigint,
  'authorId' : UserId,
  'createdAt' : Timestamp,
  'text' : string,
  'momentId' : MomentId,
}
export interface AttendanceInfo {
  'status' : string,
  'rsvpTime' : Timestamp,
  'momentDate' : Timestamp,
  'username' : string,
  'momentTitle' : string,
}
export interface Attendee {
  'rsvpStatus' : RsvpStatus,
  'userId' : UserId,
  'joinedAt' : Timestamp,
  'momentId' : MomentId,
}
export interface BulkImportMomentRow {
  'locationLat' : [] | [number],
  'locationLng' : [] | [number],
  'coverImageUrl' : [] | [string],
  'title' : string,
  'endDate' : [] | [Timestamp],
  'maxAttendees' : [] | [bigint],
  'tags' : Array<string>,
  'description' : [] | [string],
  'visibility' : string,
  'location' : [] | [string],
  'startDate' : Timestamp,
}
export interface BulkImportResult {
  'errors' : Array<{ 'row' : bigint, 'message' : string }>,
  'successCount' : bigint,
  'warnings' : Array<{ 'row' : bigint, 'message' : string }>,
}
export type CallerRelation = { 'owned' : null } |
  { 'rsvp' : RsvpStatus } |
  { 'following' : null };
export interface Comment {
  'id' : CommentId,
  'createdAt' : Timestamp,
  'text' : string,
  'author' : UserId,
  'parentId' : [] | [CommentId],
  'mediaId' : MediaId,
}
export type CommentId = bigint;
export interface ConversationInboxResult {
  'requests' : Array<ConversationSummary>,
  'accepted' : Array<ConversationSummary>,
}
export interface ConversationSummary {
  'userId' : UserId,
  'lastMessage' : Message,
  'isMessageRequest' : boolean,
  'unreadCount' : bigint,
}
export interface CreateFolderInput { 'name' : string, 'momentId' : MomentId }
export interface CreateMomentInput {
  'locationLat' : [] | [number],
  'locationLng' : [] | [number],
  'title' : string,
  'endDate' : [] | [Timestamp],
  'maxAttendees' : [] | [bigint],
  'tags' : Array<string>,
  'agendaItems' : Array<
    { 'title' : string, 'time' : string, 'description' : [] | [string] }
  >,
  'description' : string,
  'recurrence' : [] | [RecurrenceRule],
  'coverImage' : [] | [ExternalBlob],
  'visibility' : Visibility,
  'location' : string,
  'eventDate' : Timestamp,
}
export type ExternalBlob = Uint8Array;
export interface Folder {
  'id' : FolderId,
  'name' : string,
  'createdAt' : Timestamp,
  'momentId' : MomentId,
  'isDefault' : boolean,
}
export type FolderId = bigint;
export interface FollowRequest {
  'id' : string,
  'status' : FollowRequestStatus,
  'createdAt' : Timestamp,
  'toId' : UserId,
  'fromId' : UserId,
}
export type FollowRequestStatus = { 'pending' : null } |
  { 'rejected' : null } |
  { 'accepted' : null };
export interface Media {
  'id' : MediaId,
  'likeCount' : bigint,
  'blob' : ExternalBlob,
  'kind' : MediaKind,
  'createdAt' : Timestamp,
  'momentId' : MomentId,
  'filename' : string,
  'folderId' : FolderId,
  'uploadedBy' : UserId,
}
export type MediaId = bigint;
export type MediaKind = { 'audio' : null } |
  { 'video' : null } |
  { 'document' : null } |
  { 'image' : null };
export interface MediaPage {
  'total' : bigint,
  'nextOffset' : [] | [bigint],
  'items' : Array<Media>,
}
export type MemoryId = string;
export type MemoryMediaKind = { 'audio' : null } |
  { 'video' : null } |
  { 'image' : null };
export interface MemoryWithAuthor {
  'id' : MemoryId,
  'authorUsername' : string,
  'content' : string,
  'authorId' : UserId,
  'createdAt' : Timestamp,
  'momentId' : MomentId,
  'mediaBlob' : [] | [ExternalBlob],
  'mediaKind' : [] | [MemoryMediaKind],
  'authorDisplayName' : string,
}
export interface Message {
  'id' : bigint,
  'createdAt' : Timestamp,
  'text' : string,
  'isRead' : boolean,
  'recipientId' : UserId,
  'senderId' : UserId,
}
export interface MomentDetail {
  'id' : MomentId,
  'locationLat' : [] | [number],
  'locationLng' : [] | [number],
  'title' : string,
  'attendeeCount' : bigint,
  'endDate' : [] | [Timestamp],
  'callerAccessStatus' : [] | [AccessStatus],
  'owner' : UserId,
  'maxAttendees' : [] | [bigint],
  'createdAt' : Timestamp,
  'tags' : Array<string>,
  'agendaItems' : Array<AgendaItem>,
  'description' : string,
  'recurrence' : [] | [RecurrenceRule],
  'coverImage' : [] | [ExternalBlob],
  'updatedAt' : Timestamp,
  'waitlistCount' : bigint,
  'visibility' : Visibility,
  'isOwner' : boolean,
  'location' : string,
  'eventDate' : Timestamp,
}
export type MomentId = string;
export interface MomentListItem {
  'id' : MomentId,
  'locationLat' : [] | [number],
  'locationLng' : [] | [number],
  'title' : string,
  'attendeeCount' : bigint,
  'endDate' : [] | [Timestamp],
  'owner' : UserId,
  'maxAttendees' : [] | [bigint],
  'createdAt' : Timestamp,
  'tags' : Array<string>,
  'description' : string,
  'recurrence' : [] | [RecurrenceRule],
  'coverImage' : [] | [ExternalBlob],
  'occurrenceDate' : [] | [Timestamp],
  'callerRelation' : [] | [CallerRelation],
  'waitlistCount' : bigint,
  'visibility' : Visibility,
  'location' : string,
  'eventDate' : Timestamp,
}
export interface Notification {
  'id' : bigint,
  'kind' : NotificationKind,
  'createdAt' : Timestamp,
  'referenceId' : [] | [string],
  'isRead' : boolean,
  'message' : string,
  'recipientId' : UserId,
}
export type NotificationKind = { 'accessRequestResolved' : null } |
  { 'rsvpToYourMoment' : null } |
  { 'mentioned' : null } |
  { 'newAnnouncement' : null } |
  { 'newFollower' : null } |
  { 'newMessage' : null };
export interface PaymentDetail { 'value' : string, 'name' : string }
export type RecurrenceEndCondition = { 'endDate' : Timestamp } |
  { 'count' : bigint } |
  { 'never' : null };
export type RecurrenceFrequency = { 'monthly' : null } |
  { 'yearly' : null } |
  { 'daily' : null } |
  { 'weekly' : null };
export interface RecurrenceRule {
  'endCondition' : RecurrenceEndCondition,
  'interval' : bigint,
  'daysOfWeek' : Array<bigint>,
  'frequency' : RecurrenceFrequency,
}
export type RsvpStatus = { 'maybe' : null } |
  { 'notAttending' : null } |
  { 'attending' : null };
export interface SaveProfileInput {
  'username' : string,
  'hideAttendingList' : boolean,
  'name' : [] | [string],
  'socials' : [] | [Array<SocialLink>],
  'paymentDetails' : [] | [Array<PaymentDetail>],
  'isPrivateProfile' : boolean,
  'photo' : [] | [ExternalBlob],
  'location' : [] | [string],
}
export interface SocialLink { 'url' : string, 'name' : string }
export type Timestamp = bigint;
export interface UpdateMomentInput {
  'locationLat' : [] | [number],
  'locationLng' : [] | [number],
  'title' : string,
  'endDate' : [] | [Timestamp],
  'maxAttendees' : [] | [bigint],
  'tags' : Array<string>,
  'agendaItems' : Array<
    { 'title' : string, 'time' : string, 'description' : [] | [string] }
  >,
  'description' : string,
  'recurrence' : [] | [RecurrenceRule],
  'coverImage' : [] | [ExternalBlob],
  'visibility' : Visibility,
  'location' : string,
  'eventDate' : Timestamp,
}
export interface UploadMediaInput {
  'blob' : ExternalBlob,
  'kind' : MediaKind,
  'momentId' : MomentId,
  'filename' : string,
  'folderId' : FolderId,
}
export type UserId = Principal;
export interface UserProfilePublic {
  'id' : UserId,
  'username' : string,
  'hideAttendingList' : boolean,
  'followersCount' : bigint,
  'name' : [] | [string],
  'createdAt' : Timestamp,
  'socials' : [] | [Array<SocialLink>],
  'paymentDetails' : [] | [Array<PaymentDetail>],
  'isPrivateProfile' : boolean,
  'hostedCount' : bigint,
  'attendedCount' : bigint,
  'followingCount' : bigint,
  'photo' : [] | [ExternalBlob],
  'isPrivateHidden' : boolean,
  'location' : [] | [string],
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export type Visibility = { 'public' : null } |
  { 'private' : null };
export interface _ImmutableObjectStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _ImmutableObjectStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _ImmutableObjectStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_immutableObjectStorageBlobsAreLive' : ActorMethod<
    [Array<Uint8Array>],
    Array<boolean>
  >,
  '_immutableObjectStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_immutableObjectStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_immutableObjectStorageCreateCertificate' : ActorMethod<
    [string],
    _ImmutableObjectStorageCreateCertificateResult
  >,
  '_immutableObjectStorageRefillCashier' : ActorMethod<
    [[] | [_ImmutableObjectStorageRefillInformation]],
    _ImmutableObjectStorageRefillResult
  >,
  '_immutableObjectStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControl' : ActorMethod<[], undefined>,
  'acceptFollowRequest' : ActorMethod<[string], undefined>,
  'acceptMessageRequest' : ActorMethod<[UserId], undefined>,
  'addComment' : ActorMethod<[AddCommentInput], CommentId>,
  'adminBulkImportMoments' : ActorMethod<
    [Array<BulkImportMomentRow>],
    BulkImportResult
  >,
  'adminDeleteAllMoments' : ActorMethod<[], undefined>,
  'adminDeleteMedia' : ActorMethod<[MediaId], undefined>,
  'adminDeleteMoment' : ActorMethod<[MomentId], undefined>,
  'adminDeleteUser' : ActorMethod<[UserId], undefined>,
  'adminListMedia' : ActorMethod<[], Array<Media>>,
  'adminListMoments' : ActorMethod<[], Array<MomentListItem>>,
  'adminListUsers' : ActorMethod<[], Array<UserProfilePublic>>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'bookmarkMoment' : ActorMethod<[MomentId], undefined>,
  'cancelFollowRequest' : ActorMethod<[string], undefined>,
  'createFolder' : ActorMethod<[CreateFolderInput], FolderId>,
  'createMoment' : ActorMethod<[CreateMomentInput], MomentId>,
  'deleteAnnouncement' : ActorMethod<[MomentId, bigint], undefined>,
  'deleteComment' : ActorMethod<[CommentId], undefined>,
  'deleteFolder' : ActorMethod<[FolderId], undefined>,
  'deleteMedia' : ActorMethod<[MediaId], undefined>,
  'deleteMemory' : ActorMethod<
    [MemoryId],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'deleteMessageRequest' : ActorMethod<[UserId], undefined>,
  'deleteMoment' : ActorMethod<[MomentId], undefined>,
  'followUser' : ActorMethod<[UserId], boolean>,
  'getActivityFeed' : ActorMethod<[], Array<ActivityEvent>>,
  'getAnnouncementsForMoment' : ActorMethod<[MomentId], Array<Announcement>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfilePublic]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getConversation' : ActorMethod<[UserId], Array<Message>>,
  'getEventPassInfo' : ActorMethod<
    [MomentId, UserId],
    { 'ok' : AttendanceInfo } |
      { 'err' : string }
  >,
  'getFeedMoments' : ActorMethod<[], Array<MomentListItem>>,
  'getFollowRequestStatus' : ActorMethod<[UserId], [] | [FollowRequest]>,
  'getFollowers' : ActorMethod<[UserId], Array<UserProfilePublic>>,
  'getFollowing' : ActorMethod<[UserId], Array<UserProfilePublic>>,
  'getMedia' : ActorMethod<[MediaId], [] | [Media]>,
  'getMemories' : ActorMethod<
    [MomentId, bigint, [] | [Timestamp]],
    { 'ok' : Array<MemoryWithAuthor> } |
      { 'err' : string }
  >,
  'getMomentAccessStatus' : ActorMethod<[MomentId], [] | [AccessStatus]>,
  'getMomentAttendees' : ActorMethod<[MomentId], Array<Attendee>>,
  'getMomentDetail' : ActorMethod<[MomentId], [] | [MomentDetail]>,
  'getMomentPublicUrl' : ActorMethod<[MomentId], string>,
  'getMomentQrCode' : ActorMethod<[MomentId], string>,
  'getMomentShareUrl' : ActorMethod<[MomentId], string>,
  'getMomentWaitlist' : ActorMethod<[MomentId], Array<UserId>>,
  'getMomentsForUser' : ActorMethod<[UserId], Array<MomentListItem>>,
  'getMyAttendanceInfo' : ActorMethod<[MomentId], [] | [AttendanceInfo]>,
  'getMyBookmarks' : ActorMethod<[], Array<MomentId>>,
  'getMyCalendarMoments' : ActorMethod<
    [Timestamp, Timestamp],
    Array<MomentListItem>
  >,
  'getMyConversations' : ActorMethod<[], ConversationInboxResult>,
  'getMyMoments' : ActorMethod<[], Array<MomentListItem>>,
  'getMyNotifications' : ActorMethod<[], Array<Notification>>,
  'getPendingFollowRequests' : ActorMethod<[], Array<FollowRequest>>,
  'getUnreadMessageCount' : ActorMethod<[], bigint>,
  'getUnreadNotificationCount' : ActorMethod<[], bigint>,
  'getUserProfile' : ActorMethod<[UserId], [] | [UserProfilePublic]>,
  'getUserProfileByUsername' : ActorMethod<[string], [] | [UserProfilePublic]>,
  'hasLikedMedia' : ActorMethod<[MediaId], boolean>,
  'isBookmarked' : ActorMethod<[MomentId], boolean>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isFollowingUser' : ActorMethod<[UserId], boolean>,
  'isUsernameTaken' : ActorMethod<[string], boolean>,
  'listComments' : ActorMethod<[MediaId], Array<Comment>>,
  'listFolders' : ActorMethod<[MomentId], Array<Folder>>,
  'listMedia' : ActorMethod<[MomentId, bigint, bigint], MediaPage>,
  'listMediaByFolder' : ActorMethod<[FolderId, bigint, bigint], MediaPage>,
  'listMomentAccessRequests' : ActorMethod<[MomentId], Array<AccessRequest>>,
  'markAllNotificationsRead' : ActorMethod<[], undefined>,
  'markConversationRead' : ActorMethod<[UserId], undefined>,
  'markNotificationRead' : ActorMethod<[bigint], undefined>,
  'postAnnouncement' : ActorMethod<[MomentId, string], Announcement>,
  'postMemory' : ActorMethod<
    [MomentId, string, [] | [ExternalBlob], [] | [MemoryMediaKind]],
    { 'ok' : MemoryId } |
      { 'err' : string }
  >,
  'rejectFollowRequest' : ActorMethod<[string], undefined>,
  'requestMomentAccess' : ActorMethod<
    [MomentId],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'resolveAccessRequest' : ActorMethod<[MomentId, UserId, boolean], undefined>,
  'revokeMomentAccess' : ActorMethod<[MomentId, UserId], undefined>,
  'saveCallerUserProfile' : ActorMethod<[SaveProfileInput], undefined>,
  'searchMoments' : ActorMethod<
    [
      [] | [string],
      Array<string>,
      [] | [Timestamp],
      [] | [Timestamp],
      [] | [number],
      [] | [number],
      [] | [number],
      bigint,
      bigint,
    ],
    Array<MomentListItem>
  >,
  'searchUsers' : ActorMethod<[string, bigint], Array<UserProfilePublic>>,
  'sendMessage' : ActorMethod<[UserId, string], bigint>,
  'setRsvp' : ActorMethod<[MomentId, RsvpStatus], undefined>,
  'toggleLike' : ActorMethod<[MediaId], bigint>,
  'unbookmarkMoment' : ActorMethod<[MomentId], undefined>,
  'unfollowUser' : ActorMethod<[UserId], undefined>,
  'updateMoment' : ActorMethod<[MomentId, UpdateMomentInput], undefined>,
  'uploadMedia' : ActorMethod<[UploadMediaInput], MediaId>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];