/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _ImmutableObjectStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _ImmutableObjectStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _ImmutableObjectStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserId = IDL.Principal;
export const CommentId = IDL.Nat;
export const MediaId = IDL.Nat;
export const AddCommentInput = IDL.Record({
  'text' : IDL.Text,
  'parentId' : IDL.Opt(CommentId),
  'mediaId' : MediaId,
});
export const Timestamp = IDL.Int;
export const BulkImportMomentRow = IDL.Record({
  'locationLat' : IDL.Opt(IDL.Float64),
  'locationLng' : IDL.Opt(IDL.Float64),
  'coverImageUrl' : IDL.Opt(IDL.Text),
  'title' : IDL.Text,
  'endDate' : IDL.Opt(Timestamp),
  'maxAttendees' : IDL.Opt(IDL.Nat),
  'tags' : IDL.Vec(IDL.Text),
  'description' : IDL.Opt(IDL.Text),
  'visibility' : IDL.Text,
  'location' : IDL.Opt(IDL.Text),
  'startDate' : Timestamp,
});
export const BulkImportResult = IDL.Record({
  'errors' : IDL.Vec(IDL.Record({ 'row' : IDL.Nat, 'message' : IDL.Text })),
  'successCount' : IDL.Nat,
  'warnings' : IDL.Vec(IDL.Record({ 'row' : IDL.Nat, 'message' : IDL.Text })),
});
export const MomentId = IDL.Text;
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const MediaKind = IDL.Variant({
  'audio' : IDL.Null,
  'video' : IDL.Null,
  'document' : IDL.Null,
  'image' : IDL.Null,
});
export const FolderId = IDL.Nat;
export const Media = IDL.Record({
  'id' : MediaId,
  'likeCount' : IDL.Nat,
  'blob' : ExternalBlob,
  'kind' : MediaKind,
  'createdAt' : Timestamp,
  'momentId' : MomentId,
  'filename' : IDL.Text,
  'folderId' : FolderId,
  'uploadedBy' : UserId,
});
export const RecurrenceEndCondition = IDL.Variant({
  'endDate' : Timestamp,
  'count' : IDL.Nat,
  'never' : IDL.Null,
});
export const RecurrenceFrequency = IDL.Variant({
  'monthly' : IDL.Null,
  'yearly' : IDL.Null,
  'daily' : IDL.Null,
  'weekly' : IDL.Null,
});
export const RecurrenceRule = IDL.Record({
  'endCondition' : RecurrenceEndCondition,
  'interval' : IDL.Nat,
  'daysOfWeek' : IDL.Vec(IDL.Nat),
  'frequency' : RecurrenceFrequency,
});
export const RsvpStatus = IDL.Variant({
  'maybe' : IDL.Null,
  'notAttending' : IDL.Null,
  'attending' : IDL.Null,
});
export const CallerRelation = IDL.Variant({
  'owned' : IDL.Null,
  'rsvp' : RsvpStatus,
  'following' : IDL.Null,
});
export const Visibility = IDL.Variant({
  'public' : IDL.Null,
  'private' : IDL.Null,
});
export const MomentListItem = IDL.Record({
  'id' : MomentId,
  'locationLat' : IDL.Opt(IDL.Float64),
  'locationLng' : IDL.Opt(IDL.Float64),
  'title' : IDL.Text,
  'attendeeCount' : IDL.Nat,
  'endDate' : IDL.Opt(Timestamp),
  'owner' : UserId,
  'maxAttendees' : IDL.Opt(IDL.Nat),
  'createdAt' : Timestamp,
  'tags' : IDL.Vec(IDL.Text),
  'description' : IDL.Text,
  'recurrence' : IDL.Opt(RecurrenceRule),
  'coverImage' : IDL.Opt(ExternalBlob),
  'occurrenceDate' : IDL.Opt(Timestamp),
  'callerRelation' : IDL.Opt(CallerRelation),
  'waitlistCount' : IDL.Nat,
  'visibility' : Visibility,
  'location' : IDL.Text,
  'eventDate' : Timestamp,
});
export const SocialLink = IDL.Record({ 'url' : IDL.Text, 'name' : IDL.Text });
export const PaymentDetail = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const UserProfilePublic = IDL.Record({
  'id' : UserId,
  'username' : IDL.Text,
  'hideAttendingList' : IDL.Bool,
  'followersCount' : IDL.Nat,
  'name' : IDL.Opt(IDL.Text),
  'createdAt' : Timestamp,
  'socials' : IDL.Opt(IDL.Vec(SocialLink)),
  'paymentDetails' : IDL.Opt(IDL.Vec(PaymentDetail)),
  'isPrivateProfile' : IDL.Bool,
  'hostedCount' : IDL.Nat,
  'attendedCount' : IDL.Nat,
  'followingCount' : IDL.Nat,
  'photo' : IDL.Opt(ExternalBlob),
  'isPrivateHidden' : IDL.Bool,
  'location' : IDL.Opt(IDL.Text),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const CreateFolderInput = IDL.Record({
  'name' : IDL.Text,
  'momentId' : MomentId,
});
export const CreateMomentInput = IDL.Record({
  'locationLat' : IDL.Opt(IDL.Float64),
  'locationLng' : IDL.Opt(IDL.Float64),
  'title' : IDL.Text,
  'endDate' : IDL.Opt(Timestamp),
  'maxAttendees' : IDL.Opt(IDL.Nat),
  'tags' : IDL.Vec(IDL.Text),
  'agendaItems' : IDL.Vec(
    IDL.Record({
      'title' : IDL.Text,
      'time' : IDL.Text,
      'description' : IDL.Opt(IDL.Text),
    })
  ),
  'description' : IDL.Text,
  'recurrence' : IDL.Opt(RecurrenceRule),
  'coverImage' : IDL.Opt(ExternalBlob),
  'visibility' : Visibility,
  'location' : IDL.Text,
  'eventDate' : Timestamp,
});
export const MemoryId = IDL.Text;
export const ActivityKind = IDL.Variant({
  'rsvpdToMoment' : IDL.Null,
  'createdMoment' : IDL.Null,
  'followedUser' : IDL.Null,
});
export const ActivityEvent = IDL.Record({
  'id' : IDL.Nat,
  'kind' : ActivityKind,
  'createdAt' : Timestamp,
  'momentId' : IDL.Opt(MomentId),
  'actorId' : UserId,
  'targetUserId' : IDL.Opt(UserId),
});
export const Announcement = IDL.Record({
  'id' : IDL.Nat,
  'authorId' : UserId,
  'createdAt' : Timestamp,
  'text' : IDL.Text,
  'momentId' : MomentId,
});
export const Message = IDL.Record({
  'id' : IDL.Nat,
  'createdAt' : Timestamp,
  'text' : IDL.Text,
  'isRead' : IDL.Bool,
  'recipientId' : UserId,
  'senderId' : UserId,
});
export const AttendanceInfo = IDL.Record({
  'status' : IDL.Text,
  'rsvpTime' : Timestamp,
  'momentDate' : Timestamp,
  'username' : IDL.Text,
  'momentTitle' : IDL.Text,
});
export const FollowRequestStatus = IDL.Variant({
  'pending' : IDL.Null,
  'rejected' : IDL.Null,
  'accepted' : IDL.Null,
});
export const FollowRequest = IDL.Record({
  'id' : IDL.Text,
  'status' : FollowRequestStatus,
  'createdAt' : Timestamp,
  'toId' : UserId,
  'fromId' : UserId,
});
export const MemoryMediaKind = IDL.Variant({
  'audio' : IDL.Null,
  'video' : IDL.Null,
  'image' : IDL.Null,
});
export const MemoryWithAuthor = IDL.Record({
  'id' : MemoryId,
  'authorUsername' : IDL.Text,
  'content' : IDL.Text,
  'authorId' : UserId,
  'createdAt' : Timestamp,
  'momentId' : MomentId,
  'mediaBlob' : IDL.Opt(ExternalBlob),
  'mediaKind' : IDL.Opt(MemoryMediaKind),
  'authorDisplayName' : IDL.Text,
});
export const AccessStatus = IDL.Variant({
  'revoked' : IDL.Null,
  'pending' : IDL.Null,
  'denied' : IDL.Null,
  'approved' : IDL.Null,
});
export const Attendee = IDL.Record({
  'rsvpStatus' : RsvpStatus,
  'userId' : UserId,
  'joinedAt' : Timestamp,
  'momentId' : MomentId,
});
export const AgendaItem = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'time' : IDL.Text,
  'description' : IDL.Opt(IDL.Text),
});
export const MomentDetail = IDL.Record({
  'id' : MomentId,
  'locationLat' : IDL.Opt(IDL.Float64),
  'locationLng' : IDL.Opt(IDL.Float64),
  'title' : IDL.Text,
  'attendeeCount' : IDL.Nat,
  'endDate' : IDL.Opt(Timestamp),
  'callerAccessStatus' : IDL.Opt(AccessStatus),
  'owner' : UserId,
  'maxAttendees' : IDL.Opt(IDL.Nat),
  'createdAt' : Timestamp,
  'tags' : IDL.Vec(IDL.Text),
  'agendaItems' : IDL.Vec(AgendaItem),
  'description' : IDL.Text,
  'recurrence' : IDL.Opt(RecurrenceRule),
  'coverImage' : IDL.Opt(ExternalBlob),
  'updatedAt' : Timestamp,
  'waitlistCount' : IDL.Nat,
  'visibility' : Visibility,
  'isOwner' : IDL.Bool,
  'location' : IDL.Text,
  'eventDate' : Timestamp,
});
export const ConversationSummary = IDL.Record({
  'userId' : UserId,
  'lastMessage' : Message,
  'isMessageRequest' : IDL.Bool,
  'unreadCount' : IDL.Nat,
});
export const ConversationInboxResult = IDL.Record({
  'requests' : IDL.Vec(ConversationSummary),
  'accepted' : IDL.Vec(ConversationSummary),
});
export const NotificationKind = IDL.Variant({
  'accessRequestResolved' : IDL.Null,
  'rsvpToYourMoment' : IDL.Null,
  'mentioned' : IDL.Null,
  'newAnnouncement' : IDL.Null,
  'newFollower' : IDL.Null,
  'newMessage' : IDL.Null,
});
export const Notification = IDL.Record({
  'id' : IDL.Nat,
  'kind' : NotificationKind,
  'createdAt' : Timestamp,
  'referenceId' : IDL.Opt(IDL.Text),
  'isRead' : IDL.Bool,
  'message' : IDL.Text,
  'recipientId' : UserId,
});
export const Comment = IDL.Record({
  'id' : CommentId,
  'createdAt' : Timestamp,
  'text' : IDL.Text,
  'author' : UserId,
  'parentId' : IDL.Opt(CommentId),
  'mediaId' : MediaId,
});
export const Folder = IDL.Record({
  'id' : FolderId,
  'name' : IDL.Text,
  'createdAt' : Timestamp,
  'momentId' : MomentId,
  'isDefault' : IDL.Bool,
});
export const MediaPage = IDL.Record({
  'total' : IDL.Nat,
  'nextOffset' : IDL.Opt(IDL.Nat),
  'items' : IDL.Vec(Media),
});
export const AccessRequest = IDL.Record({
  'status' : AccessStatus,
  'requester' : UserId,
  'momentId' : MomentId,
  'requestedAt' : Timestamp,
  'resolvedAt' : IDL.Opt(Timestamp),
});
export const SaveProfileInput = IDL.Record({
  'username' : IDL.Text,
  'hideAttendingList' : IDL.Bool,
  'name' : IDL.Opt(IDL.Text),
  'socials' : IDL.Opt(IDL.Vec(SocialLink)),
  'paymentDetails' : IDL.Opt(IDL.Vec(PaymentDetail)),
  'isPrivateProfile' : IDL.Bool,
  'photo' : IDL.Opt(ExternalBlob),
  'location' : IDL.Opt(IDL.Text),
});
export const UpdateMomentInput = IDL.Record({
  'locationLat' : IDL.Opt(IDL.Float64),
  'locationLng' : IDL.Opt(IDL.Float64),
  'title' : IDL.Text,
  'endDate' : IDL.Opt(Timestamp),
  'maxAttendees' : IDL.Opt(IDL.Nat),
  'tags' : IDL.Vec(IDL.Text),
  'agendaItems' : IDL.Vec(
    IDL.Record({
      'title' : IDL.Text,
      'time' : IDL.Text,
      'description' : IDL.Opt(IDL.Text),
    })
  ),
  'description' : IDL.Text,
  'recurrence' : IDL.Opt(RecurrenceRule),
  'coverImage' : IDL.Opt(ExternalBlob),
  'visibility' : Visibility,
  'location' : IDL.Text,
  'eventDate' : Timestamp,
});
export const UploadMediaInput = IDL.Record({
  'blob' : ExternalBlob,
  'kind' : MediaKind,
  'momentId' : MomentId,
  'filename' : IDL.Text,
  'folderId' : FolderId,
});

export const idlService = IDL.Service({
  '_immutableObjectStorageBlobsAreLive' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [IDL.Vec(IDL.Bool)],
      ['query'],
    ),
  '_immutableObjectStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_immutableObjectStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_immutableObjectStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_ImmutableObjectStorageCreateCertificateResult],
      [],
    ),
  '_immutableObjectStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_ImmutableObjectStorageRefillInformation)],
      [_ImmutableObjectStorageRefillResult],
      [],
    ),
  '_immutableObjectStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControl' : IDL.Func([], [], []),
  'acceptFollowRequest' : IDL.Func([IDL.Text], [], []),
  'acceptMessageRequest' : IDL.Func([UserId], [], []),
  'addComment' : IDL.Func([AddCommentInput], [CommentId], []),
  'adminBulkImportMoments' : IDL.Func(
      [IDL.Vec(BulkImportMomentRow)],
      [BulkImportResult],
      [],
    ),
  'adminDeleteAllMoments' : IDL.Func([], [], []),
  'adminDeleteMedia' : IDL.Func([MediaId], [], []),
  'adminDeleteMoment' : IDL.Func([MomentId], [], []),
  'adminDeleteUser' : IDL.Func([UserId], [], []),
  'adminListMedia' : IDL.Func([], [IDL.Vec(Media)], ['query']),
  'adminListMoments' : IDL.Func([], [IDL.Vec(MomentListItem)], ['query']),
  'adminListUsers' : IDL.Func([], [IDL.Vec(UserProfilePublic)], ['query']),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'bookmarkMoment' : IDL.Func([MomentId], [], []),
  'cancelFollowRequest' : IDL.Func([IDL.Text], [], []),
  'createFolder' : IDL.Func([CreateFolderInput], [FolderId], []),
  'createMoment' : IDL.Func([CreateMomentInput], [MomentId], []),
  'deleteAnnouncement' : IDL.Func([MomentId, IDL.Nat], [], []),
  'deleteComment' : IDL.Func([CommentId], [], []),
  'deleteFolder' : IDL.Func([FolderId], [], []),
  'deleteMedia' : IDL.Func([MediaId], [], []),
  'deleteMemory' : IDL.Func(
      [MemoryId],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'deleteMessageRequest' : IDL.Func([UserId], [], []),
  'deleteMoment' : IDL.Func([MomentId], [], []),
  'followUser' : IDL.Func([UserId], [IDL.Bool], []),
  'getActivityFeed' : IDL.Func([], [IDL.Vec(ActivityEvent)], ['query']),
  'getAnnouncementsForMoment' : IDL.Func(
      [MomentId],
      [IDL.Vec(Announcement)],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func(
      [],
      [IDL.Opt(UserProfilePublic)],
      ['query'],
    ),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getConversation' : IDL.Func([UserId], [IDL.Vec(Message)], ['query']),
  'getEventPassInfo' : IDL.Func(
      [MomentId, UserId],
      [IDL.Variant({ 'ok' : AttendanceInfo, 'err' : IDL.Text })],
      ['query'],
    ),
  'getFeedMoments' : IDL.Func([], [IDL.Vec(MomentListItem)], ['query']),
  'getFollowRequestStatus' : IDL.Func(
      [UserId],
      [IDL.Opt(FollowRequest)],
      ['query'],
    ),
  'getFollowers' : IDL.Func([UserId], [IDL.Vec(UserProfilePublic)], ['query']),
  'getFollowing' : IDL.Func([UserId], [IDL.Vec(UserProfilePublic)], ['query']),
  'getMedia' : IDL.Func([MediaId], [IDL.Opt(Media)], ['query']),
  'getMemories' : IDL.Func(
      [MomentId, IDL.Nat, IDL.Opt(Timestamp)],
      [IDL.Variant({ 'ok' : IDL.Vec(MemoryWithAuthor), 'err' : IDL.Text })],
      ['query'],
    ),
  'getMomentAccessStatus' : IDL.Func(
      [MomentId],
      [IDL.Opt(AccessStatus)],
      ['query'],
    ),
  'getMomentAttendees' : IDL.Func([MomentId], [IDL.Vec(Attendee)], ['query']),
  'getMomentDetail' : IDL.Func([MomentId], [IDL.Opt(MomentDetail)], ['query']),
  'getMomentPublicUrl' : IDL.Func([MomentId], [IDL.Text], ['query']),
  'getMomentQrCode' : IDL.Func([MomentId], [IDL.Text], ['query']),
  'getMomentShareUrl' : IDL.Func([MomentId], [IDL.Text], ['query']),
  'getMomentWaitlist' : IDL.Func([MomentId], [IDL.Vec(UserId)], ['query']),
  'getMomentsForUser' : IDL.Func(
      [UserId],
      [IDL.Vec(MomentListItem)],
      ['query'],
    ),
  'getMyAttendanceInfo' : IDL.Func(
      [MomentId],
      [IDL.Opt(AttendanceInfo)],
      ['query'],
    ),
  'getMyBookmarks' : IDL.Func([], [IDL.Vec(MomentId)], ['query']),
  'getMyCalendarMoments' : IDL.Func(
      [Timestamp, Timestamp],
      [IDL.Vec(MomentListItem)],
      ['query'],
    ),
  'getMyConversations' : IDL.Func([], [ConversationInboxResult], ['query']),
  'getMyMoments' : IDL.Func([], [IDL.Vec(MomentListItem)], ['query']),
  'getMyNotifications' : IDL.Func([], [IDL.Vec(Notification)], ['query']),
  'getPendingFollowRequests' : IDL.Func(
      [],
      [IDL.Vec(FollowRequest)],
      ['query'],
    ),
  'getUnreadMessageCount' : IDL.Func([], [IDL.Nat], ['query']),
  'getUnreadNotificationCount' : IDL.Func([], [IDL.Nat], ['query']),
  'getUserProfile' : IDL.Func(
      [UserId],
      [IDL.Opt(UserProfilePublic)],
      ['query'],
    ),
  'getUserProfileByUsername' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(UserProfilePublic)],
      ['query'],
    ),
  'hasLikedMedia' : IDL.Func([MediaId], [IDL.Bool], ['query']),
  'isBookmarked' : IDL.Func([MomentId], [IDL.Bool], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isFollowingUser' : IDL.Func([UserId], [IDL.Bool], ['query']),
  'isUsernameTaken' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
  'listComments' : IDL.Func([MediaId], [IDL.Vec(Comment)], ['query']),
  'listFolders' : IDL.Func([MomentId], [IDL.Vec(Folder)], ['query']),
  'listMedia' : IDL.Func([MomentId, IDL.Nat, IDL.Nat], [MediaPage], ['query']),
  'listMediaByFolder' : IDL.Func(
      [FolderId, IDL.Nat, IDL.Nat],
      [MediaPage],
      ['query'],
    ),
  'listMomentAccessRequests' : IDL.Func(
      [MomentId],
      [IDL.Vec(AccessRequest)],
      ['query'],
    ),
  'markAllNotificationsRead' : IDL.Func([], [], []),
  'markConversationRead' : IDL.Func([UserId], [], []),
  'markNotificationRead' : IDL.Func([IDL.Nat], [], []),
  'postAnnouncement' : IDL.Func([MomentId, IDL.Text], [Announcement], []),
  'postMemory' : IDL.Func(
      [MomentId, IDL.Text, IDL.Opt(ExternalBlob), IDL.Opt(MemoryMediaKind)],
      [IDL.Variant({ 'ok' : MemoryId, 'err' : IDL.Text })],
      [],
    ),
  'rejectFollowRequest' : IDL.Func([IDL.Text], [], []),
  'requestMomentAccess' : IDL.Func(
      [MomentId],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'resolveAccessRequest' : IDL.Func([MomentId, UserId, IDL.Bool], [], []),
  'revokeMomentAccess' : IDL.Func([MomentId, UserId], [], []),
  'saveCallerUserProfile' : IDL.Func([SaveProfileInput], [], []),
  'searchMoments' : IDL.Func(
      [
        IDL.Opt(IDL.Text),
        IDL.Vec(IDL.Text),
        IDL.Opt(Timestamp),
        IDL.Opt(Timestamp),
        IDL.Opt(IDL.Float64),
        IDL.Opt(IDL.Float64),
        IDL.Opt(IDL.Float64),
        IDL.Nat,
        IDL.Nat,
      ],
      [IDL.Vec(MomentListItem)],
      ['query'],
    ),
  'searchUsers' : IDL.Func(
      [IDL.Text, IDL.Nat],
      [IDL.Vec(UserProfilePublic)],
      ['query'],
    ),
  'sendMessage' : IDL.Func([UserId, IDL.Text], [IDL.Nat], []),
  'setRsvp' : IDL.Func([MomentId, RsvpStatus], [], []),
  'toggleLike' : IDL.Func([MediaId], [IDL.Nat], []),
  'unbookmarkMoment' : IDL.Func([MomentId], [], []),
  'unfollowUser' : IDL.Func([UserId], [], []),
  'updateMoment' : IDL.Func([MomentId, UpdateMomentInput], [], []),
  'uploadMedia' : IDL.Func([UploadMediaInput], [MediaId], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _ImmutableObjectStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _ImmutableObjectStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _ImmutableObjectStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserId = IDL.Principal;
  const CommentId = IDL.Nat;
  const MediaId = IDL.Nat;
  const AddCommentInput = IDL.Record({
    'text' : IDL.Text,
    'parentId' : IDL.Opt(CommentId),
    'mediaId' : MediaId,
  });
  const Timestamp = IDL.Int;
  const BulkImportMomentRow = IDL.Record({
    'locationLat' : IDL.Opt(IDL.Float64),
    'locationLng' : IDL.Opt(IDL.Float64),
    'coverImageUrl' : IDL.Opt(IDL.Text),
    'title' : IDL.Text,
    'endDate' : IDL.Opt(Timestamp),
    'maxAttendees' : IDL.Opt(IDL.Nat),
    'tags' : IDL.Vec(IDL.Text),
    'description' : IDL.Opt(IDL.Text),
    'visibility' : IDL.Text,
    'location' : IDL.Opt(IDL.Text),
    'startDate' : Timestamp,
  });
  const BulkImportResult = IDL.Record({
    'errors' : IDL.Vec(IDL.Record({ 'row' : IDL.Nat, 'message' : IDL.Text })),
    'successCount' : IDL.Nat,
    'warnings' : IDL.Vec(IDL.Record({ 'row' : IDL.Nat, 'message' : IDL.Text })),
  });
  const MomentId = IDL.Text;
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const MediaKind = IDL.Variant({
    'audio' : IDL.Null,
    'video' : IDL.Null,
    'document' : IDL.Null,
    'image' : IDL.Null,
  });
  const FolderId = IDL.Nat;
  const Media = IDL.Record({
    'id' : MediaId,
    'likeCount' : IDL.Nat,
    'blob' : ExternalBlob,
    'kind' : MediaKind,
    'createdAt' : Timestamp,
    'momentId' : MomentId,
    'filename' : IDL.Text,
    'folderId' : FolderId,
    'uploadedBy' : UserId,
  });
  const RecurrenceEndCondition = IDL.Variant({
    'endDate' : Timestamp,
    'count' : IDL.Nat,
    'never' : IDL.Null,
  });
  const RecurrenceFrequency = IDL.Variant({
    'monthly' : IDL.Null,
    'yearly' : IDL.Null,
    'daily' : IDL.Null,
    'weekly' : IDL.Null,
  });
  const RecurrenceRule = IDL.Record({
    'endCondition' : RecurrenceEndCondition,
    'interval' : IDL.Nat,
    'daysOfWeek' : IDL.Vec(IDL.Nat),
    'frequency' : RecurrenceFrequency,
  });
  const RsvpStatus = IDL.Variant({
    'maybe' : IDL.Null,
    'notAttending' : IDL.Null,
    'attending' : IDL.Null,
  });
  const CallerRelation = IDL.Variant({
    'owned' : IDL.Null,
    'rsvp' : RsvpStatus,
    'following' : IDL.Null,
  });
  const Visibility = IDL.Variant({ 'public' : IDL.Null, 'private' : IDL.Null });
  const MomentListItem = IDL.Record({
    'id' : MomentId,
    'locationLat' : IDL.Opt(IDL.Float64),
    'locationLng' : IDL.Opt(IDL.Float64),
    'title' : IDL.Text,
    'attendeeCount' : IDL.Nat,
    'endDate' : IDL.Opt(Timestamp),
    'owner' : UserId,
    'maxAttendees' : IDL.Opt(IDL.Nat),
    'createdAt' : Timestamp,
    'tags' : IDL.Vec(IDL.Text),
    'description' : IDL.Text,
    'recurrence' : IDL.Opt(RecurrenceRule),
    'coverImage' : IDL.Opt(ExternalBlob),
    'occurrenceDate' : IDL.Opt(Timestamp),
    'callerRelation' : IDL.Opt(CallerRelation),
    'waitlistCount' : IDL.Nat,
    'visibility' : Visibility,
    'location' : IDL.Text,
    'eventDate' : Timestamp,
  });
  const SocialLink = IDL.Record({ 'url' : IDL.Text, 'name' : IDL.Text });
  const PaymentDetail = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const UserProfilePublic = IDL.Record({
    'id' : UserId,
    'username' : IDL.Text,
    'hideAttendingList' : IDL.Bool,
    'followersCount' : IDL.Nat,
    'name' : IDL.Opt(IDL.Text),
    'createdAt' : Timestamp,
    'socials' : IDL.Opt(IDL.Vec(SocialLink)),
    'paymentDetails' : IDL.Opt(IDL.Vec(PaymentDetail)),
    'isPrivateProfile' : IDL.Bool,
    'hostedCount' : IDL.Nat,
    'attendedCount' : IDL.Nat,
    'followingCount' : IDL.Nat,
    'photo' : IDL.Opt(ExternalBlob),
    'isPrivateHidden' : IDL.Bool,
    'location' : IDL.Opt(IDL.Text),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const CreateFolderInput = IDL.Record({
    'name' : IDL.Text,
    'momentId' : MomentId,
  });
  const CreateMomentInput = IDL.Record({
    'locationLat' : IDL.Opt(IDL.Float64),
    'locationLng' : IDL.Opt(IDL.Float64),
    'title' : IDL.Text,
    'endDate' : IDL.Opt(Timestamp),
    'maxAttendees' : IDL.Opt(IDL.Nat),
    'tags' : IDL.Vec(IDL.Text),
    'agendaItems' : IDL.Vec(
      IDL.Record({
        'title' : IDL.Text,
        'time' : IDL.Text,
        'description' : IDL.Opt(IDL.Text),
      })
    ),
    'description' : IDL.Text,
    'recurrence' : IDL.Opt(RecurrenceRule),
    'coverImage' : IDL.Opt(ExternalBlob),
    'visibility' : Visibility,
    'location' : IDL.Text,
    'eventDate' : Timestamp,
  });
  const MemoryId = IDL.Text;
  const ActivityKind = IDL.Variant({
    'rsvpdToMoment' : IDL.Null,
    'createdMoment' : IDL.Null,
    'followedUser' : IDL.Null,
  });
  const ActivityEvent = IDL.Record({
    'id' : IDL.Nat,
    'kind' : ActivityKind,
    'createdAt' : Timestamp,
    'momentId' : IDL.Opt(MomentId),
    'actorId' : UserId,
    'targetUserId' : IDL.Opt(UserId),
  });
  const Announcement = IDL.Record({
    'id' : IDL.Nat,
    'authorId' : UserId,
    'createdAt' : Timestamp,
    'text' : IDL.Text,
    'momentId' : MomentId,
  });
  const Message = IDL.Record({
    'id' : IDL.Nat,
    'createdAt' : Timestamp,
    'text' : IDL.Text,
    'isRead' : IDL.Bool,
    'recipientId' : UserId,
    'senderId' : UserId,
  });
  const AttendanceInfo = IDL.Record({
    'status' : IDL.Text,
    'rsvpTime' : Timestamp,
    'momentDate' : Timestamp,
    'username' : IDL.Text,
    'momentTitle' : IDL.Text,
  });
  const FollowRequestStatus = IDL.Variant({
    'pending' : IDL.Null,
    'rejected' : IDL.Null,
    'accepted' : IDL.Null,
  });
  const FollowRequest = IDL.Record({
    'id' : IDL.Text,
    'status' : FollowRequestStatus,
    'createdAt' : Timestamp,
    'toId' : UserId,
    'fromId' : UserId,
  });
  const MemoryMediaKind = IDL.Variant({
    'audio' : IDL.Null,
    'video' : IDL.Null,
    'image' : IDL.Null,
  });
  const MemoryWithAuthor = IDL.Record({
    'id' : MemoryId,
    'authorUsername' : IDL.Text,
    'content' : IDL.Text,
    'authorId' : UserId,
    'createdAt' : Timestamp,
    'momentId' : MomentId,
    'mediaBlob' : IDL.Opt(ExternalBlob),
    'mediaKind' : IDL.Opt(MemoryMediaKind),
    'authorDisplayName' : IDL.Text,
  });
  const AccessStatus = IDL.Variant({
    'revoked' : IDL.Null,
    'pending' : IDL.Null,
    'denied' : IDL.Null,
    'approved' : IDL.Null,
  });
  const Attendee = IDL.Record({
    'rsvpStatus' : RsvpStatus,
    'userId' : UserId,
    'joinedAt' : Timestamp,
    'momentId' : MomentId,
  });
  const AgendaItem = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'time' : IDL.Text,
    'description' : IDL.Opt(IDL.Text),
  });
  const MomentDetail = IDL.Record({
    'id' : MomentId,
    'locationLat' : IDL.Opt(IDL.Float64),
    'locationLng' : IDL.Opt(IDL.Float64),
    'title' : IDL.Text,
    'attendeeCount' : IDL.Nat,
    'endDate' : IDL.Opt(Timestamp),
    'callerAccessStatus' : IDL.Opt(AccessStatus),
    'owner' : UserId,
    'maxAttendees' : IDL.Opt(IDL.Nat),
    'createdAt' : Timestamp,
    'tags' : IDL.Vec(IDL.Text),
    'agendaItems' : IDL.Vec(AgendaItem),
    'description' : IDL.Text,
    'recurrence' : IDL.Opt(RecurrenceRule),
    'coverImage' : IDL.Opt(ExternalBlob),
    'updatedAt' : Timestamp,
    'waitlistCount' : IDL.Nat,
    'visibility' : Visibility,
    'isOwner' : IDL.Bool,
    'location' : IDL.Text,
    'eventDate' : Timestamp,
  });
  const ConversationSummary = IDL.Record({
    'userId' : UserId,
    'lastMessage' : Message,
    'isMessageRequest' : IDL.Bool,
    'unreadCount' : IDL.Nat,
  });
  const ConversationInboxResult = IDL.Record({
    'requests' : IDL.Vec(ConversationSummary),
    'accepted' : IDL.Vec(ConversationSummary),
  });
  const NotificationKind = IDL.Variant({
    'accessRequestResolved' : IDL.Null,
    'rsvpToYourMoment' : IDL.Null,
    'mentioned' : IDL.Null,
    'newAnnouncement' : IDL.Null,
    'newFollower' : IDL.Null,
    'newMessage' : IDL.Null,
  });
  const Notification = IDL.Record({
    'id' : IDL.Nat,
    'kind' : NotificationKind,
    'createdAt' : Timestamp,
    'referenceId' : IDL.Opt(IDL.Text),
    'isRead' : IDL.Bool,
    'message' : IDL.Text,
    'recipientId' : UserId,
  });
  const Comment = IDL.Record({
    'id' : CommentId,
    'createdAt' : Timestamp,
    'text' : IDL.Text,
    'author' : UserId,
    'parentId' : IDL.Opt(CommentId),
    'mediaId' : MediaId,
  });
  const Folder = IDL.Record({
    'id' : FolderId,
    'name' : IDL.Text,
    'createdAt' : Timestamp,
    'momentId' : MomentId,
    'isDefault' : IDL.Bool,
  });
  const MediaPage = IDL.Record({
    'total' : IDL.Nat,
    'nextOffset' : IDL.Opt(IDL.Nat),
    'items' : IDL.Vec(Media),
  });
  const AccessRequest = IDL.Record({
    'status' : AccessStatus,
    'requester' : UserId,
    'momentId' : MomentId,
    'requestedAt' : Timestamp,
    'resolvedAt' : IDL.Opt(Timestamp),
  });
  const SaveProfileInput = IDL.Record({
    'username' : IDL.Text,
    'hideAttendingList' : IDL.Bool,
    'name' : IDL.Opt(IDL.Text),
    'socials' : IDL.Opt(IDL.Vec(SocialLink)),
    'paymentDetails' : IDL.Opt(IDL.Vec(PaymentDetail)),
    'isPrivateProfile' : IDL.Bool,
    'photo' : IDL.Opt(ExternalBlob),
    'location' : IDL.Opt(IDL.Text),
  });
  const UpdateMomentInput = IDL.Record({
    'locationLat' : IDL.Opt(IDL.Float64),
    'locationLng' : IDL.Opt(IDL.Float64),
    'title' : IDL.Text,
    'endDate' : IDL.Opt(Timestamp),
    'maxAttendees' : IDL.Opt(IDL.Nat),
    'tags' : IDL.Vec(IDL.Text),
    'agendaItems' : IDL.Vec(
      IDL.Record({
        'title' : IDL.Text,
        'time' : IDL.Text,
        'description' : IDL.Opt(IDL.Text),
      })
    ),
    'description' : IDL.Text,
    'recurrence' : IDL.Opt(RecurrenceRule),
    'coverImage' : IDL.Opt(ExternalBlob),
    'visibility' : Visibility,
    'location' : IDL.Text,
    'eventDate' : Timestamp,
  });
  const UploadMediaInput = IDL.Record({
    'blob' : ExternalBlob,
    'kind' : MediaKind,
    'momentId' : MomentId,
    'filename' : IDL.Text,
    'folderId' : FolderId,
  });
  
  return IDL.Service({
    '_immutableObjectStorageBlobsAreLive' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [IDL.Vec(IDL.Bool)],
        ['query'],
      ),
    '_immutableObjectStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_immutableObjectStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_immutableObjectStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_ImmutableObjectStorageCreateCertificateResult],
        [],
      ),
    '_immutableObjectStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_ImmutableObjectStorageRefillInformation)],
        [_ImmutableObjectStorageRefillResult],
        [],
      ),
    '_immutableObjectStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControl' : IDL.Func([], [], []),
    'acceptFollowRequest' : IDL.Func([IDL.Text], [], []),
    'acceptMessageRequest' : IDL.Func([UserId], [], []),
    'addComment' : IDL.Func([AddCommentInput], [CommentId], []),
    'adminBulkImportMoments' : IDL.Func(
        [IDL.Vec(BulkImportMomentRow)],
        [BulkImportResult],
        [],
      ),
    'adminDeleteAllMoments' : IDL.Func([], [], []),
    'adminDeleteMedia' : IDL.Func([MediaId], [], []),
    'adminDeleteMoment' : IDL.Func([MomentId], [], []),
    'adminDeleteUser' : IDL.Func([UserId], [], []),
    'adminListMedia' : IDL.Func([], [IDL.Vec(Media)], ['query']),
    'adminListMoments' : IDL.Func([], [IDL.Vec(MomentListItem)], ['query']),
    'adminListUsers' : IDL.Func([], [IDL.Vec(UserProfilePublic)], ['query']),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'bookmarkMoment' : IDL.Func([MomentId], [], []),
    'cancelFollowRequest' : IDL.Func([IDL.Text], [], []),
    'createFolder' : IDL.Func([CreateFolderInput], [FolderId], []),
    'createMoment' : IDL.Func([CreateMomentInput], [MomentId], []),
    'deleteAnnouncement' : IDL.Func([MomentId, IDL.Nat], [], []),
    'deleteComment' : IDL.Func([CommentId], [], []),
    'deleteFolder' : IDL.Func([FolderId], [], []),
    'deleteMedia' : IDL.Func([MediaId], [], []),
    'deleteMemory' : IDL.Func(
        [MemoryId],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'deleteMessageRequest' : IDL.Func([UserId], [], []),
    'deleteMoment' : IDL.Func([MomentId], [], []),
    'followUser' : IDL.Func([UserId], [IDL.Bool], []),
    'getActivityFeed' : IDL.Func([], [IDL.Vec(ActivityEvent)], ['query']),
    'getAnnouncementsForMoment' : IDL.Func(
        [MomentId],
        [IDL.Vec(Announcement)],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func(
        [],
        [IDL.Opt(UserProfilePublic)],
        ['query'],
      ),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getConversation' : IDL.Func([UserId], [IDL.Vec(Message)], ['query']),
    'getEventPassInfo' : IDL.Func(
        [MomentId, UserId],
        [IDL.Variant({ 'ok' : AttendanceInfo, 'err' : IDL.Text })],
        ['query'],
      ),
    'getFeedMoments' : IDL.Func([], [IDL.Vec(MomentListItem)], ['query']),
    'getFollowRequestStatus' : IDL.Func(
        [UserId],
        [IDL.Opt(FollowRequest)],
        ['query'],
      ),
    'getFollowers' : IDL.Func(
        [UserId],
        [IDL.Vec(UserProfilePublic)],
        ['query'],
      ),
    'getFollowing' : IDL.Func(
        [UserId],
        [IDL.Vec(UserProfilePublic)],
        ['query'],
      ),
    'getMedia' : IDL.Func([MediaId], [IDL.Opt(Media)], ['query']),
    'getMemories' : IDL.Func(
        [MomentId, IDL.Nat, IDL.Opt(Timestamp)],
        [IDL.Variant({ 'ok' : IDL.Vec(MemoryWithAuthor), 'err' : IDL.Text })],
        ['query'],
      ),
    'getMomentAccessStatus' : IDL.Func(
        [MomentId],
        [IDL.Opt(AccessStatus)],
        ['query'],
      ),
    'getMomentAttendees' : IDL.Func([MomentId], [IDL.Vec(Attendee)], ['query']),
    'getMomentDetail' : IDL.Func(
        [MomentId],
        [IDL.Opt(MomentDetail)],
        ['query'],
      ),
    'getMomentPublicUrl' : IDL.Func([MomentId], [IDL.Text], ['query']),
    'getMomentQrCode' : IDL.Func([MomentId], [IDL.Text], ['query']),
    'getMomentShareUrl' : IDL.Func([MomentId], [IDL.Text], ['query']),
    'getMomentWaitlist' : IDL.Func([MomentId], [IDL.Vec(UserId)], ['query']),
    'getMomentsForUser' : IDL.Func(
        [UserId],
        [IDL.Vec(MomentListItem)],
        ['query'],
      ),
    'getMyAttendanceInfo' : IDL.Func(
        [MomentId],
        [IDL.Opt(AttendanceInfo)],
        ['query'],
      ),
    'getMyBookmarks' : IDL.Func([], [IDL.Vec(MomentId)], ['query']),
    'getMyCalendarMoments' : IDL.Func(
        [Timestamp, Timestamp],
        [IDL.Vec(MomentListItem)],
        ['query'],
      ),
    'getMyConversations' : IDL.Func([], [ConversationInboxResult], ['query']),
    'getMyMoments' : IDL.Func([], [IDL.Vec(MomentListItem)], ['query']),
    'getMyNotifications' : IDL.Func([], [IDL.Vec(Notification)], ['query']),
    'getPendingFollowRequests' : IDL.Func(
        [],
        [IDL.Vec(FollowRequest)],
        ['query'],
      ),
    'getUnreadMessageCount' : IDL.Func([], [IDL.Nat], ['query']),
    'getUnreadNotificationCount' : IDL.Func([], [IDL.Nat], ['query']),
    'getUserProfile' : IDL.Func(
        [UserId],
        [IDL.Opt(UserProfilePublic)],
        ['query'],
      ),
    'getUserProfileByUsername' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(UserProfilePublic)],
        ['query'],
      ),
    'hasLikedMedia' : IDL.Func([MediaId], [IDL.Bool], ['query']),
    'isBookmarked' : IDL.Func([MomentId], [IDL.Bool], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isFollowingUser' : IDL.Func([UserId], [IDL.Bool], ['query']),
    'isUsernameTaken' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
    'listComments' : IDL.Func([MediaId], [IDL.Vec(Comment)], ['query']),
    'listFolders' : IDL.Func([MomentId], [IDL.Vec(Folder)], ['query']),
    'listMedia' : IDL.Func(
        [MomentId, IDL.Nat, IDL.Nat],
        [MediaPage],
        ['query'],
      ),
    'listMediaByFolder' : IDL.Func(
        [FolderId, IDL.Nat, IDL.Nat],
        [MediaPage],
        ['query'],
      ),
    'listMomentAccessRequests' : IDL.Func(
        [MomentId],
        [IDL.Vec(AccessRequest)],
        ['query'],
      ),
    'markAllNotificationsRead' : IDL.Func([], [], []),
    'markConversationRead' : IDL.Func([UserId], [], []),
    'markNotificationRead' : IDL.Func([IDL.Nat], [], []),
    'postAnnouncement' : IDL.Func([MomentId, IDL.Text], [Announcement], []),
    'postMemory' : IDL.Func(
        [MomentId, IDL.Text, IDL.Opt(ExternalBlob), IDL.Opt(MemoryMediaKind)],
        [IDL.Variant({ 'ok' : MemoryId, 'err' : IDL.Text })],
        [],
      ),
    'rejectFollowRequest' : IDL.Func([IDL.Text], [], []),
    'requestMomentAccess' : IDL.Func(
        [MomentId],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'resolveAccessRequest' : IDL.Func([MomentId, UserId, IDL.Bool], [], []),
    'revokeMomentAccess' : IDL.Func([MomentId, UserId], [], []),
    'saveCallerUserProfile' : IDL.Func([SaveProfileInput], [], []),
    'searchMoments' : IDL.Func(
        [
          IDL.Opt(IDL.Text),
          IDL.Vec(IDL.Text),
          IDL.Opt(Timestamp),
          IDL.Opt(Timestamp),
          IDL.Opt(IDL.Float64),
          IDL.Opt(IDL.Float64),
          IDL.Opt(IDL.Float64),
          IDL.Nat,
          IDL.Nat,
        ],
        [IDL.Vec(MomentListItem)],
        ['query'],
      ),
    'searchUsers' : IDL.Func(
        [IDL.Text, IDL.Nat],
        [IDL.Vec(UserProfilePublic)],
        ['query'],
      ),
    'sendMessage' : IDL.Func([UserId, IDL.Text], [IDL.Nat], []),
    'setRsvp' : IDL.Func([MomentId, RsvpStatus], [], []),
    'toggleLike' : IDL.Func([MediaId], [IDL.Nat], []),
    'unbookmarkMoment' : IDL.Func([MomentId], [], []),
    'unfollowUser' : IDL.Func([UserId], [], []),
    'updateMoment' : IDL.Func([MomentId, UpdateMomentInput], [], []),
    'uploadMedia' : IDL.Func([UploadMediaInput], [MediaId], []),
  });
};

export const init = ({ IDL }) => { return []; };