/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface CreateMomentInput {
    locationLat?: number;
    locationLng?: number;
    title: string;
    tags: Array<string>;
    description: string;
    coverImage?: ExternalBlob;
    visibility: Visibility;
    location: string;
    eventDate: Timestamp;
}
export interface Attendee {
    rsvpStatus: RsvpStatus;
    userId: UserId;
    joinedAt: Timestamp;
    momentId: MomentId;
}
export type Timestamp = bigint;
export interface AccessRequest {
    status: AccessStatus;
    requester: UserId;
    momentId: MomentId;
    requestedAt: Timestamp;
    resolvedAt?: Timestamp;
}
export interface SocialLink {
    url: string;
    name: string;
}
export interface _ImmutableObjectStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export interface MomentListItem {
    id: MomentId;
    locationLat?: number;
    locationLng?: number;
    title: string;
    attendeeCount: bigint;
    owner: UserId;
    createdAt: Timestamp;
    tags: Array<string>;
    description: string;
    coverImage?: ExternalBlob;
    callerRelation?: CallerRelation;
    visibility: Visibility;
    location: string;
    eventDate: Timestamp;
}
export interface Folder {
    id: FolderId;
    name: string;
    createdAt: Timestamp;
    momentId: MomentId;
    isDefault: boolean;
}
export type MemoryId = string;
export interface MediaPage {
    total: bigint;
    nextOffset?: bigint;
    items: Array<Media>;
}
export interface Media {
    id: MediaId;
    likeCount: bigint;
    blob: ExternalBlob;
    kind: MediaKind;
    createdAt: Timestamp;
    momentId: MomentId;
    filename: string;
    folderId: FolderId;
    uploadedBy: UserId;
}
export interface PaymentDetail {
    value: string;
    name: string;
}
export interface UpdateMomentInput {
    locationLat?: number;
    locationLng?: number;
    title: string;
    tags: Array<string>;
    description: string;
    coverImage?: ExternalBlob;
    visibility: Visibility;
    location: string;
    eventDate: Timestamp;
}
export interface SaveProfileInput {
    username: string;
    name?: string;
    socials?: Array<SocialLink>;
    paymentDetails?: Array<PaymentDetail>;
    photo?: ExternalBlob;
    location?: string;
}
export type CommentId = bigint;
export interface Comment {
    id: CommentId;
    createdAt: Timestamp;
    text: string;
    author: UserId;
    parentId?: CommentId;
    mediaId: MediaId;
}
export interface AddCommentInput {
    text: string;
    parentId?: CommentId;
    mediaId: MediaId;
}
export type CallerRelation = {
    __kind__: "owned";
    owned: null;
} | {
    __kind__: "rsvp";
    rsvp: RsvpStatus;
} | {
    __kind__: "following";
    following: null;
};
export interface AttendanceInfo {
    status: string;
    rsvpTime: Timestamp;
    momentDate: Timestamp;
    username: string;
    momentTitle: string;
}
export interface _ImmutableObjectStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface MemoryWithAuthor {
    id: MemoryId;
    authorUsername: string;
    content: string;
    authorId: UserId;
    createdAt: Timestamp;
    momentId: MomentId;
    mediaBlob?: ExternalBlob;
    mediaKind?: MemoryMediaKind;
    authorDisplayName: string;
}
export interface _ImmutableObjectStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface BulkImportResult {
    errors: Array<{
        row: bigint;
        message: string;
    }>;
    successCount: bigint;
}
export interface CreateFolderInput {
    name: string;
    momentId: MomentId;
}
export interface UserProfilePublic {
    id: UserId;
    username: string;
    followersCount: bigint;
    name?: string;
    createdAt: Timestamp;
    socials?: Array<SocialLink>;
    paymentDetails?: Array<PaymentDetail>;
    followingCount: bigint;
    photo?: ExternalBlob;
    location?: string;
}
export type UserId = Principal;
export interface UploadMediaInput {
    blob: ExternalBlob;
    kind: MediaKind;
    momentId: MomentId;
    filename: string;
    folderId: FolderId;
}
export interface MomentDetail {
    id: MomentId;
    locationLat?: number;
    locationLng?: number;
    title: string;
    attendeeCount: bigint;
    callerAccessStatus?: AccessStatus;
    owner: UserId;
    createdAt: Timestamp;
    tags: Array<string>;
    description: string;
    coverImage?: ExternalBlob;
    updatedAt: Timestamp;
    visibility: Visibility;
    isOwner: boolean;
    location: string;
    eventDate: Timestamp;
}
export interface BulkImportMomentRow {
    locationLat?: number;
    locationLng?: number;
    title: string;
    endDate?: Timestamp;
    maxAttendees?: bigint;
    tags: Array<string>;
    description?: string;
    visibility: string;
    location?: string;
    startDate: Timestamp;
}
export type MomentId = string;
export type MediaId = bigint;
export type FolderId = bigint;
export enum AccessStatus {
    revoked = "revoked",
    pending = "pending",
    denied = "denied",
    approved = "approved"
}
export enum MediaKind {
    audio = "audio",
    video = "video",
    document_ = "document",
    image = "image"
}
export enum MemoryMediaKind {
    audio = "audio",
    video = "video",
    image = "image"
}
export enum RsvpStatus {
    maybe = "maybe",
    notAttending = "notAttending",
    attending = "attending"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export enum Visibility {
    public_ = "public",
    private_ = "private"
}
export interface backendInterface {
    _immutableObjectStorageBlobsAreLive(hashes: Array<Uint8Array>): Promise<Array<boolean>>;
    _immutableObjectStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _immutableObjectStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _immutableObjectStorageCreateCertificate(blobHash: string): Promise<_ImmutableObjectStorageCreateCertificateResult>;
    _immutableObjectStorageRefillCashier(refillInformation: _ImmutableObjectStorageRefillInformation | null): Promise<_ImmutableObjectStorageRefillResult>;
    _immutableObjectStorageUpdateGatewayPrincipals(): Promise<void>;
    _initializeAccessControl(): Promise<void>;
    addComment(input: AddCommentInput): Promise<CommentId>;
    adminBulkImportMoments(rows: Array<BulkImportMomentRow>): Promise<BulkImportResult>;
    adminDeleteMedia(mediaId: MediaId): Promise<void>;
    adminDeleteMoment(momentId: MomentId): Promise<void>;
    adminDeleteUser(userId: UserId): Promise<void>;
    adminListMedia(): Promise<Array<Media>>;
    adminListMoments(): Promise<Array<MomentListItem>>;
    adminListUsers(): Promise<Array<UserProfilePublic>>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    createFolder(input: CreateFolderInput): Promise<FolderId>;
    createMoment(input: CreateMomentInput): Promise<MomentId>;
    deleteComment(commentId: CommentId): Promise<void>;
    deleteFolder(folderId: FolderId): Promise<void>;
    deleteMedia(mediaId: MediaId): Promise<void>;
    deleteMemory(memoryId: MemoryId): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }>;
    deleteMoment(momentId: MomentId): Promise<void>;
    followUser(target: UserId): Promise<void>;
    getCallerUserProfile(): Promise<UserProfilePublic | null>;
    getCallerUserRole(): Promise<UserRole>;
    getFeedMoments(): Promise<Array<MomentListItem>>;
    getFollowers(userId: UserId): Promise<Array<UserProfilePublic>>;
    getFollowing(userId: UserId): Promise<Array<UserProfilePublic>>;
    getMedia(mediaId: MediaId): Promise<Media | null>;
    getMemories(momentId: MomentId, limit: bigint, before: Timestamp | null): Promise<{
        __kind__: "ok";
        ok: Array<MemoryWithAuthor>;
    } | {
        __kind__: "err";
        err: string;
    }>;
    getMomentAccessStatus(momentId: MomentId): Promise<AccessStatus | null>;
    getMomentAttendees(momentId: MomentId): Promise<Array<Attendee>>;
    getMomentDetail(momentId: MomentId): Promise<MomentDetail | null>;
    getMomentPublicUrl(momentId: MomentId): Promise<string>;
    getMomentQrCode(momentId: MomentId): Promise<string>;
    getMomentShareUrl(momentId: MomentId): Promise<string>;
    getMomentsForUser(userId: UserId): Promise<Array<MomentListItem>>;
    getMyAttendanceInfo(momentId: MomentId): Promise<AttendanceInfo | null>;
    getMyCalendarMoments(): Promise<Array<MomentListItem>>;
    getMyMoments(): Promise<Array<MomentListItem>>;
    getUserProfile(userId: UserId): Promise<UserProfilePublic | null>;
    getUserProfileByUsername(username: string): Promise<UserProfilePublic | null>;
    hasLikedMedia(mediaId: MediaId): Promise<boolean>;
    isCallerAdmin(): Promise<boolean>;
    isFollowingUser(target: UserId): Promise<boolean>;
    isUsernameTaken(username: string): Promise<boolean>;
    listComments(mediaId: MediaId): Promise<Array<Comment>>;
    listFolders(momentId: MomentId): Promise<Array<Folder>>;
    listMedia(momentId: MomentId, offset: bigint, limit: bigint): Promise<MediaPage>;
    listMediaByFolder(folderId: FolderId, offset: bigint, limit: bigint): Promise<MediaPage>;
    listMomentAccessRequests(momentId: MomentId): Promise<Array<AccessRequest>>;
    postMemory(momentId: MomentId, content: string, mediaBlob: ExternalBlob | null, mediaKind: MemoryMediaKind | null): Promise<{
        __kind__: "ok";
        ok: MemoryId;
    } | {
        __kind__: "err";
        err: string;
    }>;
    requestMomentAccess(momentId: MomentId): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }>;
    resolveAccessRequest(momentId: MomentId, requester: UserId, approved: boolean): Promise<void>;
    revokeMomentAccess(momentId: MomentId, userId: UserId): Promise<void>;
    saveCallerUserProfile(input: SaveProfileInput): Promise<void>;
    searchMoments(searchText: string | null, tags: Array<string>, offset: bigint, limit: bigint): Promise<Array<MomentListItem>>;
    setRsvp(momentId: MomentId, status: RsvpStatus): Promise<void>;
    toggleLike(mediaId: MediaId): Promise<bigint>;
    unfollowUser(target: UserId): Promise<void>;
    updateMoment(momentId: MomentId, input: UpdateMomentInput): Promise<void>;
    uploadMedia(input: UploadMediaInput): Promise<MediaId>;
}
import type { AccessRequest as _AccessRequest, AccessStatus as _AccessStatus, AddCommentInput as _AddCommentInput, AttendanceInfo as _AttendanceInfo, Attendee as _Attendee, BulkImportMomentRow as _BulkImportMomentRow, CallerRelation as _CallerRelation, Comment as _Comment, CommentId as _CommentId, CreateMomentInput as _CreateMomentInput, ExternalBlob as _ExternalBlob, FolderId as _FolderId, Media as _Media, MediaId as _MediaId, MediaKind as _MediaKind, MediaPage as _MediaPage, MemoryId as _MemoryId, MemoryMediaKind as _MemoryMediaKind, MemoryWithAuthor as _MemoryWithAuthor, MomentDetail as _MomentDetail, MomentId as _MomentId, MomentListItem as _MomentListItem, PaymentDetail as _PaymentDetail, RsvpStatus as _RsvpStatus, SaveProfileInput as _SaveProfileInput, SocialLink as _SocialLink, Timestamp as _Timestamp, UpdateMomentInput as _UpdateMomentInput, UploadMediaInput as _UploadMediaInput, UserId as _UserId, UserProfilePublic as _UserProfilePublic, UserRole as _UserRole, Visibility as _Visibility, _ImmutableObjectStorageRefillInformation as __ImmutableObjectStorageRefillInformation, _ImmutableObjectStorageRefillResult as __ImmutableObjectStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _immutableObjectStorageBlobsAreLive(arg0: Array<Uint8Array>): Promise<Array<boolean>> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageBlobsAreLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageBlobsAreLive(arg0);
            return result;
        }
    }
    async _immutableObjectStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageBlobsToDelete();
            return result;
        }
    }
    async _immutableObjectStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _immutableObjectStorageCreateCertificate(arg0: string): Promise<_ImmutableObjectStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _immutableObjectStorageRefillCashier(arg0: _ImmutableObjectStorageRefillInformation | null): Promise<_ImmutableObjectStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__ImmutableObjectStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__ImmutableObjectStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _immutableObjectStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async _initializeAccessControl(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControl();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControl();
            return result;
        }
    }
    async addComment(arg0: AddCommentInput): Promise<CommentId> {
        if (this.processError) {
            try {
                const result = await this.actor.addComment(to_candid_AddCommentInput_n8(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addComment(to_candid_AddCommentInput_n8(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async adminBulkImportMoments(arg0: Array<BulkImportMomentRow>): Promise<BulkImportResult> {
        if (this.processError) {
            try {
                const result = await this.actor.adminBulkImportMoments(to_candid_vec_n10(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminBulkImportMoments(to_candid_vec_n10(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async adminDeleteMedia(arg0: MediaId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.adminDeleteMedia(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminDeleteMedia(arg0);
            return result;
        }
    }
    async adminDeleteMoment(arg0: MomentId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.adminDeleteMoment(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminDeleteMoment(arg0);
            return result;
        }
    }
    async adminDeleteUser(arg0: UserId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.adminDeleteUser(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminDeleteUser(arg0);
            return result;
        }
    }
    async adminListMedia(): Promise<Array<Media>> {
        if (this.processError) {
            try {
                const result = await this.actor.adminListMedia();
                return from_candid_vec_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminListMedia();
            return from_candid_vec_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async adminListMoments(): Promise<Array<MomentListItem>> {
        if (this.processError) {
            try {
                const result = await this.actor.adminListMoments();
                return from_candid_vec_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminListMoments();
            return from_candid_vec_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async adminListUsers(): Promise<Array<UserProfilePublic>> {
        if (this.processError) {
            try {
                const result = await this.actor.adminListUsers();
                return from_candid_vec_n31(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminListUsers();
            return from_candid_vec_n31(this._uploadFile, this._downloadFile, result);
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n37(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n37(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async createFolder(arg0: CreateFolderInput): Promise<FolderId> {
        if (this.processError) {
            try {
                const result = await this.actor.createFolder(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createFolder(arg0);
            return result;
        }
    }
    async createMoment(arg0: CreateMomentInput): Promise<MomentId> {
        if (this.processError) {
            try {
                const result = await this.actor.createMoment(await to_candid_CreateMomentInput_n39(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createMoment(await to_candid_CreateMomentInput_n39(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async deleteComment(arg0: CommentId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteComment(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteComment(arg0);
            return result;
        }
    }
    async deleteFolder(arg0: FolderId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteFolder(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteFolder(arg0);
            return result;
        }
    }
    async deleteMedia(arg0: MediaId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteMedia(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteMedia(arg0);
            return result;
        }
    }
    async deleteMemory(arg0: MemoryId): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteMemory(arg0);
                return from_candid_variant_n44(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteMemory(arg0);
            return from_candid_variant_n44(this._uploadFile, this._downloadFile, result);
        }
    }
    async deleteMoment(arg0: MomentId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteMoment(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteMoment(arg0);
            return result;
        }
    }
    async followUser(arg0: UserId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.followUser(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.followUser(arg0);
            return result;
        }
    }
    async getCallerUserProfile(): Promise<UserProfilePublic | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n45(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n45(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n46(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n46(this._uploadFile, this._downloadFile, result);
        }
    }
    async getFeedMoments(): Promise<Array<MomentListItem>> {
        if (this.processError) {
            try {
                const result = await this.actor.getFeedMoments();
                return from_candid_vec_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFeedMoments();
            return from_candid_vec_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async getFollowers(arg0: UserId): Promise<Array<UserProfilePublic>> {
        if (this.processError) {
            try {
                const result = await this.actor.getFollowers(arg0);
                return from_candid_vec_n31(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFollowers(arg0);
            return from_candid_vec_n31(this._uploadFile, this._downloadFile, result);
        }
    }
    async getFollowing(arg0: UserId): Promise<Array<UserProfilePublic>> {
        if (this.processError) {
            try {
                const result = await this.actor.getFollowing(arg0);
                return from_candid_vec_n31(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFollowing(arg0);
            return from_candid_vec_n31(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMedia(arg0: MediaId): Promise<Media | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getMedia(arg0);
                return from_candid_opt_n48(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMedia(arg0);
            return from_candid_opt_n48(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMemories(arg0: MomentId, arg1: bigint, arg2: Timestamp | null): Promise<{
        __kind__: "ok";
        ok: Array<MemoryWithAuthor>;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getMemories(arg0, arg1, to_candid_opt_n49(this._uploadFile, this._downloadFile, arg2));
                return from_candid_variant_n50(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMemories(arg0, arg1, to_candid_opt_n49(this._uploadFile, this._downloadFile, arg2));
            return from_candid_variant_n50(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMomentAccessStatus(arg0: MomentId): Promise<AccessStatus | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getMomentAccessStatus(arg0);
                return from_candid_opt_n57(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMomentAccessStatus(arg0);
            return from_candid_opt_n57(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMomentAttendees(arg0: MomentId): Promise<Array<Attendee>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMomentAttendees(arg0);
                return from_candid_vec_n60(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMomentAttendees(arg0);
            return from_candid_vec_n60(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMomentDetail(arg0: MomentId): Promise<MomentDetail | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getMomentDetail(arg0);
                return from_candid_opt_n63(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMomentDetail(arg0);
            return from_candid_opt_n63(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMomentPublicUrl(arg0: MomentId): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.getMomentPublicUrl(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMomentPublicUrl(arg0);
            return result;
        }
    }
    async getMomentQrCode(arg0: MomentId): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.getMomentQrCode(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMomentQrCode(arg0);
            return result;
        }
    }
    async getMomentShareUrl(arg0: MomentId): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.getMomentShareUrl(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMomentShareUrl(arg0);
            return result;
        }
    }
    async getMomentsForUser(arg0: UserId): Promise<Array<MomentListItem>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMomentsForUser(arg0);
                return from_candid_vec_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMomentsForUser(arg0);
            return from_candid_vec_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyAttendanceInfo(arg0: MomentId): Promise<AttendanceInfo | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyAttendanceInfo(arg0);
                return from_candid_opt_n66(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyAttendanceInfo(arg0);
            return from_candid_opt_n66(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyCalendarMoments(): Promise<Array<MomentListItem>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyCalendarMoments();
                return from_candid_vec_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyCalendarMoments();
            return from_candid_vec_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyMoments(): Promise<Array<MomentListItem>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyMoments();
                return from_candid_vec_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyMoments();
            return from_candid_vec_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: UserId): Promise<UserProfilePublic | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n45(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n45(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfileByUsername(arg0: string): Promise<UserProfilePublic | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfileByUsername(arg0);
                return from_candid_opt_n45(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfileByUsername(arg0);
            return from_candid_opt_n45(this._uploadFile, this._downloadFile, result);
        }
    }
    async hasLikedMedia(arg0: MediaId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.hasLikedMedia(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.hasLikedMedia(arg0);
            return result;
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async isFollowingUser(arg0: UserId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isFollowingUser(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isFollowingUser(arg0);
            return result;
        }
    }
    async isUsernameTaken(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isUsernameTaken(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isUsernameTaken(arg0);
            return result;
        }
    }
    async listComments(arg0: MediaId): Promise<Array<Comment>> {
        if (this.processError) {
            try {
                const result = await this.actor.listComments(arg0);
                return from_candid_vec_n67(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listComments(arg0);
            return from_candid_vec_n67(this._uploadFile, this._downloadFile, result);
        }
    }
    async listFolders(arg0: MomentId): Promise<Array<Folder>> {
        if (this.processError) {
            try {
                const result = await this.actor.listFolders(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listFolders(arg0);
            return result;
        }
    }
    async listMedia(arg0: MomentId, arg1: bigint, arg2: bigint): Promise<MediaPage> {
        if (this.processError) {
            try {
                const result = await this.actor.listMedia(arg0, arg1, arg2);
                return from_candid_MediaPage_n71(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listMedia(arg0, arg1, arg2);
            return from_candid_MediaPage_n71(this._uploadFile, this._downloadFile, result);
        }
    }
    async listMediaByFolder(arg0: FolderId, arg1: bigint, arg2: bigint): Promise<MediaPage> {
        if (this.processError) {
            try {
                const result = await this.actor.listMediaByFolder(arg0, arg1, arg2);
                return from_candid_MediaPage_n71(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listMediaByFolder(arg0, arg1, arg2);
            return from_candid_MediaPage_n71(this._uploadFile, this._downloadFile, result);
        }
    }
    async listMomentAccessRequests(arg0: MomentId): Promise<Array<AccessRequest>> {
        if (this.processError) {
            try {
                const result = await this.actor.listMomentAccessRequests(arg0);
                return from_candid_vec_n73(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listMomentAccessRequests(arg0);
            return from_candid_vec_n73(this._uploadFile, this._downloadFile, result);
        }
    }
    async postMemory(arg0: MomentId, arg1: string, arg2: ExternalBlob | null, arg3: MemoryMediaKind | null): Promise<{
        __kind__: "ok";
        ok: MemoryId;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.postMemory(arg0, arg1, await to_candid_opt_n77(this._uploadFile, this._downloadFile, arg2), to_candid_opt_n78(this._uploadFile, this._downloadFile, arg3));
                return from_candid_variant_n81(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.postMemory(arg0, arg1, await to_candid_opt_n77(this._uploadFile, this._downloadFile, arg2), to_candid_opt_n78(this._uploadFile, this._downloadFile, arg3));
            return from_candid_variant_n81(this._uploadFile, this._downloadFile, result);
        }
    }
    async requestMomentAccess(arg0: MomentId): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.requestMomentAccess(arg0);
                return from_candid_variant_n44(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.requestMomentAccess(arg0);
            return from_candid_variant_n44(this._uploadFile, this._downloadFile, result);
        }
    }
    async resolveAccessRequest(arg0: MomentId, arg1: UserId, arg2: boolean): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.resolveAccessRequest(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.resolveAccessRequest(arg0, arg1, arg2);
            return result;
        }
    }
    async revokeMomentAccess(arg0: MomentId, arg1: UserId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.revokeMomentAccess(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.revokeMomentAccess(arg0, arg1);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: SaveProfileInput): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(await to_candid_SaveProfileInput_n82(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(await to_candid_SaveProfileInput_n82(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async searchMoments(arg0: string | null, arg1: Array<string>, arg2: bigint, arg3: bigint): Promise<Array<MomentListItem>> {
        if (this.processError) {
            try {
                const result = await this.actor.searchMoments(to_candid_opt_n84(this._uploadFile, this._downloadFile, arg0), arg1, arg2, arg3);
                return from_candid_vec_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.searchMoments(to_candid_opt_n84(this._uploadFile, this._downloadFile, arg0), arg1, arg2, arg3);
            return from_candid_vec_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async setRsvp(arg0: MomentId, arg1: RsvpStatus): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setRsvp(arg0, to_candid_RsvpStatus_n85(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setRsvp(arg0, to_candid_RsvpStatus_n85(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async toggleLike(arg0: MediaId): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.toggleLike(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.toggleLike(arg0);
            return result;
        }
    }
    async unfollowUser(arg0: UserId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.unfollowUser(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.unfollowUser(arg0);
            return result;
        }
    }
    async updateMoment(arg0: MomentId, arg1: UpdateMomentInput): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateMoment(arg0, await to_candid_UpdateMomentInput_n87(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateMoment(arg0, await to_candid_UpdateMomentInput_n87(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async uploadMedia(arg0: UploadMediaInput): Promise<MediaId> {
        if (this.processError) {
            try {
                const result = await this.actor.uploadMedia(await to_candid_UploadMediaInput_n88(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.uploadMedia(await to_candid_UploadMediaInput_n88(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
}
function from_candid_AccessRequest_n74(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AccessRequest): AccessRequest {
    return from_candid_record_n75(_uploadFile, _downloadFile, value);
}
function from_candid_AccessStatus_n58(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AccessStatus): AccessStatus {
    return from_candid_variant_n59(_uploadFile, _downloadFile, value);
}
function from_candid_Attendee_n61(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Attendee): Attendee {
    return from_candid_record_n62(_uploadFile, _downloadFile, value);
}
function from_candid_CallerRelation_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CallerRelation): CallerRelation {
    return from_candid_variant_n26(_uploadFile, _downloadFile, value);
}
function from_candid_Comment_n68(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Comment): Comment {
    return from_candid_record_n69(_uploadFile, _downloadFile, value);
}
async function from_candid_ExternalBlob_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ExternalBlob): Promise<ExternalBlob> {
    return await _downloadFile(value);
}
function from_candid_MediaKind_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _MediaKind): MediaKind {
    return from_candid_variant_n18(_uploadFile, _downloadFile, value);
}
async function from_candid_MediaPage_n71(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _MediaPage): Promise<MediaPage> {
    return await from_candid_record_n72(_uploadFile, _downloadFile, value);
}
async function from_candid_Media_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Media): Promise<Media> {
    return await from_candid_record_n15(_uploadFile, _downloadFile, value);
}
function from_candid_MemoryMediaKind_n55(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _MemoryMediaKind): MemoryMediaKind {
    return from_candid_variant_n56(_uploadFile, _downloadFile, value);
}
async function from_candid_MemoryWithAuthor_n52(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _MemoryWithAuthor): Promise<MemoryWithAuthor> {
    return await from_candid_record_n53(_uploadFile, _downloadFile, value);
}
async function from_candid_MomentDetail_n64(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _MomentDetail): Promise<MomentDetail> {
    return await from_candid_record_n65(_uploadFile, _downloadFile, value);
}
async function from_candid_MomentListItem_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _MomentListItem): Promise<MomentListItem> {
    return await from_candid_record_n21(_uploadFile, _downloadFile, value);
}
function from_candid_RsvpStatus_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _RsvpStatus): RsvpStatus {
    return from_candid_variant_n28(_uploadFile, _downloadFile, value);
}
async function from_candid_UserProfilePublic_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfilePublic): Promise<UserProfilePublic> {
    return await from_candid_record_n33(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n47(_uploadFile, _downloadFile, value);
}
function from_candid_Visibility_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Visibility): Visibility {
    return from_candid_variant_n30(_uploadFile, _downloadFile, value);
}
function from_candid__ImmutableObjectStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __ImmutableObjectStorageRefillResult): _ImmutableObjectStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [number]): number | null {
    return value.length === 0 ? null : value[0];
}
async function from_candid_opt_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ExternalBlob]): Promise<ExternalBlob | null> {
    return value.length === 0 ? null : await from_candid_ExternalBlob_n16(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_CallerRelation]): CallerRelation | null {
    return value.length === 0 ? null : from_candid_CallerRelation_n25(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [Array<_SocialLink>]): Array<SocialLink> | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [Array<_PaymentDetail>]): Array<PaymentDetail> | null {
    return value.length === 0 ? null : value[0];
}
async function from_candid_opt_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfilePublic]): Promise<UserProfilePublic | null> {
    return value.length === 0 ? null : await from_candid_UserProfilePublic_n32(_uploadFile, _downloadFile, value[0]);
}
async function from_candid_opt_n48(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Media]): Promise<Media | null> {
    return value.length === 0 ? null : await from_candid_Media_n14(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n54(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_MemoryMediaKind]): MemoryMediaKind | null {
    return value.length === 0 ? null : from_candid_MemoryMediaKind_n55(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n57(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_AccessStatus]): AccessStatus | null {
    return value.length === 0 ? null : from_candid_AccessStatus_n58(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
async function from_candid_opt_n63(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_MomentDetail]): Promise<MomentDetail | null> {
    return value.length === 0 ? null : await from_candid_MomentDetail_n64(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n66(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_AttendanceInfo]): AttendanceInfo | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n70(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_CommentId]): CommentId | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n76(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Timestamp]): Timestamp | null {
    return value.length === 0 ? null : value[0];
}
async function from_candid_record_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _MediaId;
    likeCount: bigint;
    blob: _ExternalBlob;
    kind: _MediaKind;
    createdAt: _Timestamp;
    momentId: _MomentId;
    filename: string;
    folderId: _FolderId;
    uploadedBy: _UserId;
}): Promise<{
    id: MediaId;
    likeCount: bigint;
    blob: ExternalBlob;
    kind: MediaKind;
    createdAt: Timestamp;
    momentId: MomentId;
    filename: string;
    folderId: FolderId;
    uploadedBy: UserId;
}> {
    return {
        id: value.id,
        likeCount: value.likeCount,
        blob: await from_candid_ExternalBlob_n16(_uploadFile, _downloadFile, value.blob),
        kind: from_candid_MediaKind_n17(_uploadFile, _downloadFile, value.kind),
        createdAt: value.createdAt,
        momentId: value.momentId,
        filename: value.filename,
        folderId: value.folderId,
        uploadedBy: value.uploadedBy
    };
}
async function from_candid_record_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _MomentId;
    locationLat: [] | [number];
    locationLng: [] | [number];
    title: string;
    attendeeCount: bigint;
    owner: _UserId;
    createdAt: _Timestamp;
    tags: Array<string>;
    description: string;
    coverImage: [] | [_ExternalBlob];
    callerRelation: [] | [_CallerRelation];
    visibility: _Visibility;
    location: string;
    eventDate: _Timestamp;
}): Promise<{
    id: MomentId;
    locationLat?: number;
    locationLng?: number;
    title: string;
    attendeeCount: bigint;
    owner: UserId;
    createdAt: Timestamp;
    tags: Array<string>;
    description: string;
    coverImage?: ExternalBlob;
    callerRelation?: CallerRelation;
    visibility: Visibility;
    location: string;
    eventDate: Timestamp;
}> {
    return {
        id: value.id,
        locationLat: record_opt_to_undefined(from_candid_opt_n22(_uploadFile, _downloadFile, value.locationLat)),
        locationLng: record_opt_to_undefined(from_candid_opt_n22(_uploadFile, _downloadFile, value.locationLng)),
        title: value.title,
        attendeeCount: value.attendeeCount,
        owner: value.owner,
        createdAt: value.createdAt,
        tags: value.tags,
        description: value.description,
        coverImage: record_opt_to_undefined(await from_candid_opt_n23(_uploadFile, _downloadFile, value.coverImage)),
        callerRelation: record_opt_to_undefined(from_candid_opt_n24(_uploadFile, _downloadFile, value.callerRelation)),
        visibility: from_candid_Visibility_n29(_uploadFile, _downloadFile, value.visibility),
        location: value.location,
        eventDate: value.eventDate
    };
}
async function from_candid_record_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _UserId;
    username: string;
    followersCount: bigint;
    name: [] | [string];
    createdAt: _Timestamp;
    socials: [] | [Array<_SocialLink>];
    paymentDetails: [] | [Array<_PaymentDetail>];
    followingCount: bigint;
    photo: [] | [_ExternalBlob];
    location: [] | [string];
}): Promise<{
    id: UserId;
    username: string;
    followersCount: bigint;
    name?: string;
    createdAt: Timestamp;
    socials?: Array<SocialLink>;
    paymentDetails?: Array<PaymentDetail>;
    followingCount: bigint;
    photo?: ExternalBlob;
    location?: string;
}> {
    return {
        id: value.id,
        username: value.username,
        followersCount: value.followersCount,
        name: record_opt_to_undefined(from_candid_opt_n34(_uploadFile, _downloadFile, value.name)),
        createdAt: value.createdAt,
        socials: record_opt_to_undefined(from_candid_opt_n35(_uploadFile, _downloadFile, value.socials)),
        paymentDetails: record_opt_to_undefined(from_candid_opt_n36(_uploadFile, _downloadFile, value.paymentDetails)),
        followingCount: value.followingCount,
        photo: record_opt_to_undefined(await from_candid_opt_n23(_uploadFile, _downloadFile, value.photo)),
        location: record_opt_to_undefined(from_candid_opt_n34(_uploadFile, _downloadFile, value.location))
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
async function from_candid_record_n53(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _MemoryId;
    authorUsername: string;
    content: string;
    authorId: _UserId;
    createdAt: _Timestamp;
    momentId: _MomentId;
    mediaBlob: [] | [_ExternalBlob];
    mediaKind: [] | [_MemoryMediaKind];
    authorDisplayName: string;
}): Promise<{
    id: MemoryId;
    authorUsername: string;
    content: string;
    authorId: UserId;
    createdAt: Timestamp;
    momentId: MomentId;
    mediaBlob?: ExternalBlob;
    mediaKind?: MemoryMediaKind;
    authorDisplayName: string;
}> {
    return {
        id: value.id,
        authorUsername: value.authorUsername,
        content: value.content,
        authorId: value.authorId,
        createdAt: value.createdAt,
        momentId: value.momentId,
        mediaBlob: record_opt_to_undefined(await from_candid_opt_n23(_uploadFile, _downloadFile, value.mediaBlob)),
        mediaKind: record_opt_to_undefined(from_candid_opt_n54(_uploadFile, _downloadFile, value.mediaKind)),
        authorDisplayName: value.authorDisplayName
    };
}
function from_candid_record_n62(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    rsvpStatus: _RsvpStatus;
    userId: _UserId;
    joinedAt: _Timestamp;
    momentId: _MomentId;
}): {
    rsvpStatus: RsvpStatus;
    userId: UserId;
    joinedAt: Timestamp;
    momentId: MomentId;
} {
    return {
        rsvpStatus: from_candid_RsvpStatus_n27(_uploadFile, _downloadFile, value.rsvpStatus),
        userId: value.userId,
        joinedAt: value.joinedAt,
        momentId: value.momentId
    };
}
async function from_candid_record_n65(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _MomentId;
    locationLat: [] | [number];
    locationLng: [] | [number];
    title: string;
    attendeeCount: bigint;
    callerAccessStatus: [] | [_AccessStatus];
    owner: _UserId;
    createdAt: _Timestamp;
    tags: Array<string>;
    description: string;
    coverImage: [] | [_ExternalBlob];
    updatedAt: _Timestamp;
    visibility: _Visibility;
    isOwner: boolean;
    location: string;
    eventDate: _Timestamp;
}): Promise<{
    id: MomentId;
    locationLat?: number;
    locationLng?: number;
    title: string;
    attendeeCount: bigint;
    callerAccessStatus?: AccessStatus;
    owner: UserId;
    createdAt: Timestamp;
    tags: Array<string>;
    description: string;
    coverImage?: ExternalBlob;
    updatedAt: Timestamp;
    visibility: Visibility;
    isOwner: boolean;
    location: string;
    eventDate: Timestamp;
}> {
    return {
        id: value.id,
        locationLat: record_opt_to_undefined(from_candid_opt_n22(_uploadFile, _downloadFile, value.locationLat)),
        locationLng: record_opt_to_undefined(from_candid_opt_n22(_uploadFile, _downloadFile, value.locationLng)),
        title: value.title,
        attendeeCount: value.attendeeCount,
        callerAccessStatus: record_opt_to_undefined(from_candid_opt_n57(_uploadFile, _downloadFile, value.callerAccessStatus)),
        owner: value.owner,
        createdAt: value.createdAt,
        tags: value.tags,
        description: value.description,
        coverImage: record_opt_to_undefined(await from_candid_opt_n23(_uploadFile, _downloadFile, value.coverImage)),
        updatedAt: value.updatedAt,
        visibility: from_candid_Visibility_n29(_uploadFile, _downloadFile, value.visibility),
        isOwner: value.isOwner,
        location: value.location,
        eventDate: value.eventDate
    };
}
function from_candid_record_n69(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _CommentId;
    createdAt: _Timestamp;
    text: string;
    author: _UserId;
    parentId: [] | [_CommentId];
    mediaId: _MediaId;
}): {
    id: CommentId;
    createdAt: Timestamp;
    text: string;
    author: UserId;
    parentId?: CommentId;
    mediaId: MediaId;
} {
    return {
        id: value.id,
        createdAt: value.createdAt,
        text: value.text,
        author: value.author,
        parentId: record_opt_to_undefined(from_candid_opt_n70(_uploadFile, _downloadFile, value.parentId)),
        mediaId: value.mediaId
    };
}
async function from_candid_record_n72(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    total: bigint;
    nextOffset: [] | [bigint];
    items: Array<_Media>;
}): Promise<{
    total: bigint;
    nextOffset?: bigint;
    items: Array<Media>;
}> {
    return {
        total: value.total,
        nextOffset: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.nextOffset)),
        items: await from_candid_vec_n13(_uploadFile, _downloadFile, value.items)
    };
}
function from_candid_record_n75(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: _AccessStatus;
    requester: _UserId;
    momentId: _MomentId;
    requestedAt: _Timestamp;
    resolvedAt: [] | [_Timestamp];
}): {
    status: AccessStatus;
    requester: UserId;
    momentId: MomentId;
    requestedAt: Timestamp;
    resolvedAt?: Timestamp;
} {
    return {
        status: from_candid_AccessStatus_n58(_uploadFile, _downloadFile, value.status),
        requester: value.requester,
        momentId: value.momentId,
        requestedAt: value.requestedAt,
        resolvedAt: record_opt_to_undefined(from_candid_opt_n76(_uploadFile, _downloadFile, value.resolvedAt))
    };
}
function from_candid_variant_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    audio: null;
} | {
    video: null;
} | {
    document: null;
} | {
    image: null;
}): MediaKind {
    return "audio" in value ? MediaKind.audio : "video" in value ? MediaKind.video : "document" in value ? MediaKind.document : "image" in value ? MediaKind.image : value;
}
function from_candid_variant_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    owned: null;
} | {
    rsvp: _RsvpStatus;
} | {
    following: null;
}): {
    __kind__: "owned";
    owned: null;
} | {
    __kind__: "rsvp";
    rsvp: RsvpStatus;
} | {
    __kind__: "following";
    following: null;
} {
    return "owned" in value ? {
        __kind__: "owned",
        owned: value.owned
    } : "rsvp" in value ? {
        __kind__: "rsvp",
        rsvp: from_candid_RsvpStatus_n27(_uploadFile, _downloadFile, value.rsvp)
    } : "following" in value ? {
        __kind__: "following",
        following: value.following
    } : value;
}
function from_candid_variant_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    maybe: null;
} | {
    notAttending: null;
} | {
    attending: null;
}): RsvpStatus {
    return "maybe" in value ? RsvpStatus.maybe : "notAttending" in value ? RsvpStatus.notAttending : "attending" in value ? RsvpStatus.attending : value;
}
function from_candid_variant_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    public: null;
} | {
    private: null;
}): Visibility {
    return "public" in value ? Visibility.public : "private" in value ? Visibility.private : value;
}
function from_candid_variant_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: null;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: null;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n47(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
async function from_candid_variant_n50(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: Array<_MemoryWithAuthor>;
} | {
    err: string;
}): Promise<{
    __kind__: "ok";
    ok: Array<MemoryWithAuthor>;
} | {
    __kind__: "err";
    err: string;
}> {
    return "ok" in value ? {
        __kind__: "ok",
        ok: await from_candid_vec_n51(_uploadFile, _downloadFile, value.ok)
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n56(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    audio: null;
} | {
    video: null;
} | {
    image: null;
}): MemoryMediaKind {
    return "audio" in value ? MemoryMediaKind.audio : "video" in value ? MemoryMediaKind.video : "image" in value ? MemoryMediaKind.image : value;
}
function from_candid_variant_n59(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    revoked: null;
} | {
    pending: null;
} | {
    denied: null;
} | {
    approved: null;
}): AccessStatus {
    return "revoked" in value ? AccessStatus.revoked : "pending" in value ? AccessStatus.pending : "denied" in value ? AccessStatus.denied : "approved" in value ? AccessStatus.approved : value;
}
function from_candid_variant_n81(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _MemoryId;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: MemoryId;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
async function from_candid_vec_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Media>): Promise<Array<Media>> {
    return await Promise.all(value.map(async (x)=>await from_candid_Media_n14(_uploadFile, _downloadFile, x)));
}
async function from_candid_vec_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_MomentListItem>): Promise<Array<MomentListItem>> {
    return await Promise.all(value.map(async (x)=>await from_candid_MomentListItem_n20(_uploadFile, _downloadFile, x)));
}
async function from_candid_vec_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_UserProfilePublic>): Promise<Array<UserProfilePublic>> {
    return await Promise.all(value.map(async (x)=>await from_candid_UserProfilePublic_n32(_uploadFile, _downloadFile, x)));
}
async function from_candid_vec_n51(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_MemoryWithAuthor>): Promise<Array<MemoryWithAuthor>> {
    return await Promise.all(value.map(async (x)=>await from_candid_MemoryWithAuthor_n52(_uploadFile, _downloadFile, x)));
}
function from_candid_vec_n60(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Attendee>): Array<Attendee> {
    return value.map((x)=>from_candid_Attendee_n61(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n67(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Comment>): Array<Comment> {
    return value.map((x)=>from_candid_Comment_n68(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n73(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_AccessRequest>): Array<AccessRequest> {
    return value.map((x)=>from_candid_AccessRequest_n74(_uploadFile, _downloadFile, x));
}
function to_candid_AddCommentInput_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AddCommentInput): _AddCommentInput {
    return to_candid_record_n9(_uploadFile, _downloadFile, value);
}
function to_candid_BulkImportMomentRow_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: BulkImportMomentRow): _BulkImportMomentRow {
    return to_candid_record_n12(_uploadFile, _downloadFile, value);
}
async function to_candid_CreateMomentInput_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CreateMomentInput): Promise<_CreateMomentInput> {
    return await to_candid_record_n40(_uploadFile, _downloadFile, value);
}
async function to_candid_ExternalBlob_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExternalBlob): Promise<_ExternalBlob> {
    return await _uploadFile(value);
}
function to_candid_MediaKind_n90(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: MediaKind): _MediaKind {
    return to_candid_variant_n91(_uploadFile, _downloadFile, value);
}
function to_candid_MemoryMediaKind_n79(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: MemoryMediaKind): _MemoryMediaKind {
    return to_candid_variant_n80(_uploadFile, _downloadFile, value);
}
function to_candid_RsvpStatus_n85(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: RsvpStatus): _RsvpStatus {
    return to_candid_variant_n86(_uploadFile, _downloadFile, value);
}
async function to_candid_SaveProfileInput_n82(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SaveProfileInput): Promise<_SaveProfileInput> {
    return await to_candid_record_n83(_uploadFile, _downloadFile, value);
}
async function to_candid_UpdateMomentInput_n87(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UpdateMomentInput): Promise<_UpdateMomentInput> {
    return await to_candid_record_n40(_uploadFile, _downloadFile, value);
}
async function to_candid_UploadMediaInput_n88(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UploadMediaInput): Promise<_UploadMediaInput> {
    return await to_candid_record_n89(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n38(_uploadFile, _downloadFile, value);
}
function to_candid_Visibility_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Visibility): _Visibility {
    return to_candid_variant_n43(_uploadFile, _downloadFile, value);
}
function to_candid__ImmutableObjectStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ImmutableObjectStorageRefillInformation): __ImmutableObjectStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ImmutableObjectStorageRefillInformation | null): [] | [__ImmutableObjectStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__ImmutableObjectStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
function to_candid_opt_n49(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Timestamp | null): [] | [_Timestamp] {
    return value === null ? candid_none() : candid_some(value);
}
async function to_candid_opt_n77(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExternalBlob | null): Promise<[] | [_ExternalBlob]> {
    return value === null ? candid_none() : candid_some(await to_candid_ExternalBlob_n41(_uploadFile, _downloadFile, value));
}
function to_candid_opt_n78(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: MemoryMediaKind | null): [] | [_MemoryMediaKind] {
    return value === null ? candid_none() : candid_some(to_candid_MemoryMediaKind_n79(_uploadFile, _downloadFile, value));
}
function to_candid_opt_n84(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_record_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    locationLat?: number;
    locationLng?: number;
    title: string;
    endDate?: Timestamp;
    maxAttendees?: bigint;
    tags: Array<string>;
    description?: string;
    visibility: string;
    location?: string;
    startDate: Timestamp;
}): {
    locationLat: [] | [number];
    locationLng: [] | [number];
    title: string;
    endDate: [] | [_Timestamp];
    maxAttendees: [] | [bigint];
    tags: Array<string>;
    description: [] | [string];
    visibility: string;
    location: [] | [string];
    startDate: _Timestamp;
} {
    return {
        locationLat: value.locationLat ? candid_some(value.locationLat) : candid_none(),
        locationLng: value.locationLng ? candid_some(value.locationLng) : candid_none(),
        title: value.title,
        endDate: value.endDate ? candid_some(value.endDate) : candid_none(),
        maxAttendees: value.maxAttendees ? candid_some(value.maxAttendees) : candid_none(),
        tags: value.tags,
        description: value.description ? candid_some(value.description) : candid_none(),
        visibility: value.visibility,
        location: value.location ? candid_some(value.location) : candid_none(),
        startDate: value.startDate
    };
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
async function to_candid_record_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    locationLat?: number;
    locationLng?: number;
    title: string;
    tags: Array<string>;
    description: string;
    coverImage?: ExternalBlob;
    visibility: Visibility;
    location: string;
    eventDate: Timestamp;
}): Promise<{
    locationLat: [] | [number];
    locationLng: [] | [number];
    title: string;
    tags: Array<string>;
    description: string;
    coverImage: [] | [_ExternalBlob];
    visibility: _Visibility;
    location: string;
    eventDate: _Timestamp;
}> {
    return {
        locationLat: value.locationLat ? candid_some(value.locationLat) : candid_none(),
        locationLng: value.locationLng ? candid_some(value.locationLng) : candid_none(),
        title: value.title,
        tags: value.tags,
        description: value.description,
        coverImage: value.coverImage ? candid_some(await to_candid_ExternalBlob_n41(_uploadFile, _downloadFile, value.coverImage)) : candid_none(),
        visibility: to_candid_Visibility_n42(_uploadFile, _downloadFile, value.visibility),
        location: value.location,
        eventDate: value.eventDate
    };
}
async function to_candid_record_n83(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    username: string;
    name?: string;
    socials?: Array<SocialLink>;
    paymentDetails?: Array<PaymentDetail>;
    photo?: ExternalBlob;
    location?: string;
}): Promise<{
    username: string;
    name: [] | [string];
    socials: [] | [Array<_SocialLink>];
    paymentDetails: [] | [Array<_PaymentDetail>];
    photo: [] | [_ExternalBlob];
    location: [] | [string];
}> {
    return {
        username: value.username,
        name: value.name ? candid_some(value.name) : candid_none(),
        socials: value.socials ? candid_some(value.socials) : candid_none(),
        paymentDetails: value.paymentDetails ? candid_some(value.paymentDetails) : candid_none(),
        photo: value.photo ? candid_some(await to_candid_ExternalBlob_n41(_uploadFile, _downloadFile, value.photo)) : candid_none(),
        location: value.location ? candid_some(value.location) : candid_none()
    };
}
async function to_candid_record_n89(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    blob: ExternalBlob;
    kind: MediaKind;
    momentId: MomentId;
    filename: string;
    folderId: FolderId;
}): Promise<{
    blob: _ExternalBlob;
    kind: _MediaKind;
    momentId: _MomentId;
    filename: string;
    folderId: _FolderId;
}> {
    return {
        blob: await to_candid_ExternalBlob_n41(_uploadFile, _downloadFile, value.blob),
        kind: to_candid_MediaKind_n90(_uploadFile, _downloadFile, value.kind),
        momentId: value.momentId,
        filename: value.filename,
        folderId: value.folderId
    };
}
function to_candid_record_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    text: string;
    parentId?: CommentId;
    mediaId: MediaId;
}): {
    text: string;
    parentId: [] | [_CommentId];
    mediaId: _MediaId;
} {
    return {
        text: value.text,
        parentId: value.parentId ? candid_some(value.parentId) : candid_none(),
        mediaId: value.mediaId
    };
}
function to_candid_variant_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Visibility): {
    public: null;
} | {
    private: null;
} {
    return value == Visibility.public ? {
        public_: null
    } : value == Visibility.private ? {
        private_: null
    } : value;
}
function to_candid_variant_n80(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: MemoryMediaKind): {
    audio: null;
} | {
    video: null;
} | {
    image: null;
} {
    return value == MemoryMediaKind.audio ? {
        audio: null
    } : value == MemoryMediaKind.video ? {
        video: null
    } : value == MemoryMediaKind.image ? {
        image: null
    } : value;
}
function to_candid_variant_n86(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: RsvpStatus): {
    maybe: null;
} | {
    notAttending: null;
} | {
    attending: null;
} {
    return value == RsvpStatus.maybe ? {
        maybe: null
    } : value == RsvpStatus.notAttending ? {
        notAttending: null
    } : value == RsvpStatus.attending ? {
        attending: null
    } : value;
}
function to_candid_variant_n91(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: MediaKind): {
    audio: null;
} | {
    video: null;
} | {
    document: null;
} | {
    image: null;
} {
    return value == MediaKind.audio ? {
        audio: null
    } : value == MediaKind.video ? {
        video: null
    } : value == MediaKind.document ? {
        document_: null
    } : value == MediaKind.image ? {
        image: null
    } : value;
}
function to_candid_vec_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<BulkImportMomentRow>): Array<_BulkImportMomentRow> {
    return value.map((x)=>to_candid_BulkImportMomentRow_n11(_uploadFile, _downloadFile, x));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
